import Link from 'next/link';
import { and, desc, eq } from 'drizzle-orm';
import { EnterpriseAccountActions } from '@/components/enterprise-account-actions';
import { EnterpriseApplicationEvent, EnterpriseParticipation, EnterpriseWorkspaceClient } from '@/components/enterprise-workspace-client';
import { getDb } from '@/db';
import { appointmentResponses, appointments, demandSupplyPosts, enterprises, eventExhibitors, eventFeatures, events, exhibitorProfileVersions, inquiries, productVersions, products, userNotifications } from '@/db/schema';
import { getCurrentEnterpriseActor } from '@/lib/enterprise-auth';

function parse(value?: string | null) { try { return JSON.parse(value ?? '{}') as Record<string, unknown>; } catch { return {}; } }

export default async function EnterpriseWorkspacePage() {
  const actor = await getCurrentEnterpriseActor();
  if (!actor) return <main className="company-gate"><span className="brand-mark">企</span><h1>企业工作台需要登录</h1><p>企业资料、产品、展位和询盘仅返回当前企业账号的数据。</p><Link className="primary-button button-link" href="/company-workspace/login?returnTo=/company-workspace">企业账号登录</Link><Link href="/exhibition/2026-morocco">返回公开门户</Link></main>;
  const db = getDb();
  const exhibitorRows = await db.select({ id: eventExhibitors.id, eventId: eventExhibitors.eventId, qualificationStatus: eventExhibitors.qualificationStatus, publishStatus: eventExhibitors.publishStatus, boothNo: eventExhibitors.boothNo, category: eventExhibitors.category, applicationIntent: eventExhibitors.description, currentVersionId: eventExhibitors.currentVersionId, eventName: events.name, shortName: events.shortName, slug: events.slug, year: events.year, eventStatus: events.status, venueText: events.venueText, startAt: events.startAt, endAt: events.endAt }).from(eventExhibitors).innerJoin(events, eq(eventExhibitors.eventId, events.id)).where(eq(eventExhibitors.enterpriseId, actor.enterpriseId)).orderBy(desc(events.year));
  const [allProfiles, eventRows, featureRows, allProducts, allProductVersions, allInquiries, allPosts, allAppointments, allResponses, allEventExhibitors, allEnterprises, notifications] = await Promise.all([
    db.select().from(exhibitorProfileVersions).orderBy(desc(exhibitorProfileVersions.versionNo)), db.select().from(events).orderBy(desc(events.year)), db.select().from(eventFeatures), db.select().from(products), db.select().from(productVersions).orderBy(desc(productVersions.versionNo)), db.select().from(inquiries).orderBy(desc(inquiries.createdAt)), db.select().from(demandSupplyPosts).orderBy(desc(demandSupplyPosts.createdAt)), db.select().from(appointments).orderBy(desc(appointments.createdAt)), db.select().from(appointmentResponses), db.select().from(eventExhibitors), db.select().from(enterprises),
    db.select().from(userNotifications).where(and(eq(userNotifications.recipientType, 'ENTERPRISE_ACCOUNT'), eq(userNotifications.recipientAccountId, actor.accountId))).orderBy(desc(userNotifications.createdAt)),
  ]);
  const participations: EnterpriseParticipation[] = exhibitorRows.map(row => {
    const profileRows = allProfiles.filter(profile => profile.eventExhibitorId === row.id); const currentProfile = profileRows.find(profile => profile.id === row.currentVersionId); const pendingProfile = profileRows.find(profile => profile.reviewStatus === 'PENDING');
    const matchingEnabled = Boolean(featureRows.find(item => item.eventId === row.eventId && item.featureCode === 'MATCHING')?.enabled);
    const counterparties = allEventExhibitors.filter(item => item.eventId === row.eventId && item.enterpriseId !== actor.enterpriseId && item.qualificationStatus === 'APPROVED').map(item => allEnterprises.find(enterprise => enterprise.id === item.enterpriseId)).filter((item): item is NonNullable<typeof item> => Boolean(item)).map(item => ({ id: item.id, name: item.nameZh }));
    return { ...row, matchingEnabled, currentProfile: currentProfile ? { id: currentProfile.id, versionNo: currentProfile.versionNo, status: currentProfile.reviewStatus, data: parse(currentProfile.profileJson) } : null, pendingProfile: pendingProfile ? { id: pendingProfile.id, versionNo: pendingProfile.versionNo, status: pendingProfile.reviewStatus, data: parse(pendingProfile.profileJson) } : null, products: allProducts.filter(product => product.eventExhibitorId === row.id).map(product => { const versions = allProductVersions.filter(version => version.productId === product.id); const current = versions.find(version => version.id === product.currentVersionId); const pending = versions.find(version => version.reviewStatus === 'PENDING'); return { id: product.id, name: product.name, category: product.category, publishStatus: product.publishStatus, current: current ? { id: current.id, versionNo: current.versionNo, data: parse(current.contentJson) } : null, pending: pending ? { id: pending.id, versionNo: pending.versionNo, data: parse(pending.contentJson) } : null }; }), inquiries: allInquiries.filter(inquiry => inquiry.eventExhibitorId === row.id).map(inquiry => ({ id: inquiry.id, customerName: inquiry.customerName, contactPrivate: inquiry.contactPrivate, content: inquiry.content, status: inquiry.status, createdAt: inquiry.createdAt, handledBy: inquiry.handledBy })), posts: allPosts.filter(post => post.eventId === row.eventId && post.publisherEnterpriseId === actor.enterpriseId), marketPosts: allPosts.filter(post => post.eventId === row.eventId && post.publisherEnterpriseId !== actor.enterpriseId && post.reviewStatus === 'PUBLISHED'), counterparties, appointments: allAppointments.filter(item => item.eventId === row.eventId && [item.inviterEnterpriseId, item.inviteeEnterpriseId].includes(actor.enterpriseId)).map(item => ({ ...item, direction: item.inviterEnterpriseId === actor.enterpriseId ? 'OUTGOING' : 'INCOMING', responses: allResponses.filter(response => response.appointmentId === item.id) })) };
  });
  const applicationEvents: EnterpriseApplicationEvent[] = eventRows.filter(event => {
    if (event.status === 'ARCHIVED') return false;
    const feature = featureRows.find(item => item.eventId === event.id && item.featureCode === 'EXHIBITOR');
    if (!feature?.enabled) return false;
    try { if ((JSON.parse(feature.configJson) as { applicationOpen?: boolean }).applicationOpen === false) return false; } catch { /* 缺省开放 */ }
    const participation = participations.find(item => item.eventId === event.id);
    return !participation || participation.qualificationStatus === 'REJECTED';
  }).map(event => ({ id: event.id, name: event.name, shortName: event.shortName, year: event.year, city: event.city, country: event.country, startAt: event.startAt }));
  return <main className="company-workspace"><header><Link href="/exhibition/2026-morocco"><span className="brand-mark">企</span><strong>会展中枢 · 企业工作台</strong></Link><div><span>{actor.enterpriseName}</span><small>{actor.displayName}</small></div><EnterpriseAccountActions/></header><EnterpriseWorkspaceClient enterpriseName={actor.enterpriseName} displayName={actor.displayName} identityText={actor.identities.map(item => item.displayMasked).join(' / ')} participations={participations} applicationEvents={applicationEvents} notifications={notifications.map((item) => ({ id: item.id, category: item.category, title: item.title, body: item.body, href: item.href, status: item.status, readAt: item.readAt, createdAt: item.createdAt }))}/></main>;
}
