import Link from 'next/link';
import { AdminShell } from '@/components/admin-shell';
import { AnalyticsRunsPanel } from '@/components/analytics-runs-panel';
import { getDb } from '@/db';
import { appointments, channelVisitHistory, conversionEvents, demandSupplyPosts, eventExhibitors, events, inquiries, messageDeliveries, messageTasks, metricDefinitions, metricSnapshotRuns, metricSnapshots, products, promotionChannels, registrationRecords, reportRuns } from '@/db/schema';
import { getCurrentSessionActor, hasEventPermission } from '@/lib/auth';

type Params={year?:string;eventId?:string};
const statusName:Record<string,string>={DRAFT:'草稿',PREPARING:'筹备中',PUBLISHED:'已发布',ONGOING:'进行中',ENDED:'已结束',ARCHIVED:'已归档'};

export default async function AnalyticsPage({searchParams}:{searchParams:Promise<Params>}){
  const actor=await getCurrentSessionActor();
  if(!actor)return <AdminShell active="/analytics" title="集团数据全景"><section className="panel empty-state">请先登录后查看数据资产。</section></AdminShell>;
  const params=await searchParams;const db=getDb();
  const allEvents=await db.select().from(events);const accessible=actor.groupRole==='GROUP_ADMIN'?allEvents:allEvents.filter(event=>actor.memberships.some(member=>member.eventId===event.id));
  const years=[...new Set(accessible.map(event=>event.year))].sort((a,b)=>b-a);const selectedYear=Number(params.year)||years[0]||new Date().getFullYear();
  const yearEvents=accessible.filter(event=>event.year===selectedYear);const selectedEvents=params.eventId?yearEvents.filter(event=>event.id===params.eventId):yearEvents;const selectedIds=new Set(selectedEvents.map(event=>event.id));
  const[definitions,allSnapshotRuns,allSnapshots,allReportRuns]=await Promise.all([db.select().from(metricDefinitions),db.select().from(metricSnapshotRuns),db.select().from(metricSnapshots),db.select().from(reportRuns)]);const selectedEventId=params.eventId??null;const scopeKey=selectedEventId?`EVENT:${selectedEventId}`:`YEAR:${selectedYear}`;const scopedSnapshotRuns=allSnapshotRuns.filter(row=>row.scopeKey===scopeKey).sort((a,b)=>b.startedAt.localeCompare(a.startedAt)).slice(0,8);const latestSuccess=scopedSnapshotRuns.find(row=>row.status==='SUCCESS');const latestSnapshots=latestSuccess?allSnapshots.filter(row=>row.runId===latestSuccess.id):[];const scopedReportRuns=allReportRuns.filter(row=>row.year===selectedYear&&row.eventId===selectedEventId).sort((a,b)=>b.startedAt.localeCompare(a.startedAt)).slice(0,8);const canRun=selectedEventId?hasEventPermission(actor,selectedEventId,'event.analytics.view'):actor.groupRole==='GROUP_ADMIN';
  const[registrations,exhibitors,allProducts,allInquiries,posts,allAppointments,channels,visits,conversions,tasks,deliveries]=await Promise.all([db.select().from(registrationRecords),db.select().from(eventExhibitors),db.select().from(products),db.select().from(inquiries),db.select().from(demandSupplyPosts),db.select().from(appointments),db.select().from(promotionChannels),db.select().from(channelVisitHistory),db.select().from(conversionEvents),db.select().from(messageTasks),db.select().from(messageDeliveries)]);
  const scopedRegistrations=registrations.filter(row=>selectedIds.has(row.eventId));const scopedExhibitors=exhibitors.filter(row=>selectedIds.has(row.eventId));const scopedProducts=allProducts.filter(row=>selectedIds.has(row.eventId));const scopedInquiries=allInquiries.filter(row=>selectedIds.has(row.eventId));const scopedPosts=posts.filter(row=>selectedIds.has(row.eventId));const scopedAppointments=allAppointments.filter(row=>selectedIds.has(row.eventId));const scopedChannels=channels.filter(row=>selectedIds.has(row.eventId));const scopedVisits=visits.filter(row=>selectedIds.has(row.eventId));const scopedConversions=conversions.filter(row=>selectedIds.has(row.eventId));const scopedTasks=tasks.filter(row=>selectedIds.has(row.eventId));const taskIds=new Set(scopedTasks.map(row=>row.id));const scopedDeliveries=deliveries.filter(row=>taskIds.has(row.taskId));
  const checkedIn=scopedRegistrations.filter(row=>row.status==='CHECKED_IN').length;const approvedExhibitors=scopedExhibitors.filter(row=>row.qualificationStatus==='APPROVED').length;const uniqueAccounts=new Set(scopedRegistrations.map(row=>row.accountId)).size;
  const eventRows=selectedEvents.map(event=>{const regs=registrations.filter(row=>row.eventId===event.id);const firms=exhibitors.filter(row=>row.eventId===event.id);return{...event,registrations:regs.length,uniqueAccounts:new Set(regs.map(row=>row.accountId)).size,checkedIn:regs.filter(row=>row.status==='CHECKED_IN').length,exhibitors:firms.filter(row=>row.qualificationStatus==='APPROVED').length,inquiries:allInquiries.filter(row=>row.eventId===event.id).length,appointments:allAppointments.filter(row=>row.eventId===event.id).length}});
  const maxRegistration=Math.max(1,...eventRows.map(row=>row.registrations));const submitted=scopedConversions.filter(row=>row.conversionType==='REGISTRATION_SUBMITTED');const channelRows=scopedChannels.map(channel=>({name:channel.name,count:new Set(submitted.filter(item=>item.channelId===channel.id).map(item=>item.objectId)).size})).filter(row=>row.count>0);const channelTotal=Math.max(1,channelRows.reduce((sum,row)=>sum+row.count,0));
  const now=new Date();const realtimeAt=now.toLocaleString('zh-CN',{hour12:false});const hourlyAt=new Date(Math.floor(now.getTime()/3600000)*3600000).toLocaleString('zh-CN',{hour12:false});const query=`year=${selectedYear}${params.eventId?`&eventId=${encodeURIComponent(params.eventId)}`:''}`;
  return <AdminShell active="/analytics" title="集团数据全景" eyebrow={`集团工作台 / ${selectedYear} / ${params.eventId?'展会下钻':'年度全景'}`} actions={<a className="ghost-button" href={`/api/analytics/export?${query}`}>导出实时聚合CSV</a>}>
    <section className="analytics-filters"><div><strong>年度</strong>{years.map(year=><Link className={year===selectedYear?'active':''} href={`/analytics?year=${year}`} key={year}>{year}</Link>)}</div><div><strong>展会</strong><Link className={!params.eventId?'active':''} href={`/analytics?year=${selectedYear}`}>全部</Link>{yearEvents.map(event=><Link className={params.eventId===event.id?'active':''} href={`/analytics?year=${selectedYear}&eventId=${event.id}`} key={event.id}>{event.shortName}</Link>)}</div></section>
    <section className="module-summary"><div><span>当前范围展会</span><strong>{selectedEvents.length}</strong><small>年度与具体展会可下钻</small></div><div><span>报名记录 / 账号</span><strong>{scopedRegistrations.length} / {uniqueAccounts}</strong><small>重复报名事实继续保留</small></div><div><span>已通过企业 / 签到</span><strong>{approvedExhibitors} / {checkedIn}</strong><small>按业务状态实时聚合</small></div><div><span>数据更新时间</span><strong className="time-value">{now.toLocaleTimeString('zh-CN',{hour12:false,hour:'2-digit',minute:'2-digit'})}</strong><small>复杂指标整点 {hourlyAt.slice(-8,-3)}</small></div></section>
    <section className="analytics-note"><strong>统计口径 v1.0</strong><span>报名同时展示记录数与去重账号数；企业按资格通过计数；渠道转化按报名记录去重。业务状态近实时，复杂指标可在下方运行中心固化为小时快照。</span><small>本页计算于 {realtimeAt}</small></section>
    <section className="content-grid"><article className="panel"><div className="panel-head"><div><span className="eyebrow">EVENT MATRIX</span><h2>{params.eventId?'当前展会规模':'年度项目矩阵'}</h2></div><span className="soft-pill">{selectedYear}</span></div>{eventRows.length?<div className="year-bars">{eventRows.map(row=><div key={row.id}><span>{row.shortName}</span><i style={{height:`${Math.max(8,Math.round(row.registrations/maxRegistration*100))}%`}}/><strong>{row.registrations}</strong></div>)}</div>:<div className="empty-state">当前筛选范围没有展会。</div>}</article><article className="panel"><div className="panel-head"><div><span className="eyebrow">FIRST-TOUCH CONVERSION</span><h2>首次渠道报名贡献</h2></div></div>{channelRows.length?<div className="channel-list">{channelRows.map(item=>{const percent=Math.round(item.count/channelTotal*100);return <div key={item.name}><span>{item.name}</span><div className="track"><i style={{width:`${percent}%`}}/></div><strong>{item.count} · {percent}%</strong></div>})}</div>:<div className="empty-state">当前范围暂无带渠道归因的报名。</div>}</article></section>
    <section className="analytics-domain-grid"><article><span>内容与访问</span><strong>{scopedVisits.length}</strong><small>有效渠道访问；新闻/PV事件模型待扩展</small></article><article><span>产品与询盘</span><strong>{scopedProducts.length} / {scopedInquiries.length}</strong><small>产品记录 / 询盘记录</small></article><article><span>供需与预约</span><strong>{scopedPosts.length} / {scopedAppointments.length}</strong><small>供需记录 / 预约记录</small></article><article><span>消息回执</span><strong>{scopedDeliveries.filter(row=>row.status==='SUCCESS').length} / {scopedDeliveries.length}</strong><small>成功 / 全部模拟回执</small></article></section>
    <AnalyticsRunsPanel year={selectedYear} eventId={selectedEventId} canRun={canRun} definitions={definitions} snapshotRuns={scopedSnapshotRuns} latestSnapshots={latestSnapshots} reportRuns={scopedReportRuns}/>
    <section className="panel"><div className="panel-head"><div><span className="eyebrow">DRILLDOWN TABLE</span><h2>展会事实对照</h2></div></div><div className="data-table"><table><thead><tr><th>展会</th><th>状态</th><th>报名/账号</th><th>签到</th><th>通过企业</th><th>询盘</th><th>预约</th><th>操作</th></tr></thead><tbody>{eventRows.map(row=><tr key={row.id}><td><strong>{row.name}</strong></td><td>{statusName[row.status]??row.status}</td><td>{row.registrations} / {row.uniqueAccounts}</td><td>{row.checkedIn}</td><td>{row.exhibitors}</td><td>{row.inquiries}</td><td>{row.appointments}</td><td><Link href={`/analytics?year=${selectedYear}&eventId=${row.id}`}>下钻</Link></td></tr>)}</tbody></table></div></section>
  </AdminShell>;
}
