import { AdminShell } from '@/components/admin-shell';
import { DataAssetsWorkspace } from '@/components/data-assets-workspace';
import { SensitiveExportPanel } from '@/components/sensitive-export-panel';
import { DataImportPanel } from '@/components/data-import-panel';
import { getDb } from '@/db';
import { appointments, checkinLogs, dataImportJobs, dataMergeRecords, demandSupplyPosts, enterprises, eventExhibitors, events, inquiries, personMasters, products, publicAccounts, publicIdentities, registrationRecords, sensitiveExportDownloadLogs, sensitiveExportFiles, sensitiveExportRequests } from '@/db/schema';
import { getCurrentSessionActor } from '@/lib/auth';
import { getCurrentEventId } from '@/lib/current-event';
import { sensitiveExportFieldOptions } from '@/lib/sensitive-export';

export default async function DataAssetsPage(){const[actor,currentEventId]=await Promise.all([getCurrentSessionActor(),getCurrentEventId()]);if(!actor||actor.groupRole!=='GROUP_ADMIN')return <AdminShell active="/data-assets" title="集团数据资产"><section className="planned-panel"><span>权限受限</span><h2>需要集团数据管理权限</h2><p>人员和企业主档跨展会汇总，仅集团管理员可查看与执行合并。</p></section></AdminShell>;
  const db=getDb();const[persons,accounts,identities,registrations,checkins,enterpriseRows,participations,productRows,inquiryRows,posts,appointmentRows,eventRows,merges]=await Promise.all([db.select().from(personMasters),db.select().from(publicAccounts),db.select().from(publicIdentities),db.select().from(registrationRecords),db.select().from(checkinLogs),db.select().from(enterprises),db.select().from(eventExhibitors),db.select().from(products),db.select().from(inquiries),db.select().from(demandSupplyPosts),db.select().from(appointments),db.select().from(events),db.select().from(dataMergeRecords)]);const eventMap=new Map(eventRows.map(item=>[item.id,`${item.year} · ${item.shortName}`]));
  const personItems=persons.map(person=>{const ownedAccounts=accounts.filter(item=>item.personMasterId===person.id);const accountIds=ownedAccounts.map(item=>item.id);const ownedRegistrations=registrations.filter(item=>accountIds.includes(item.accountId));const recordIds=ownedRegistrations.map(item=>item.id);const ownedPosts=posts.filter(item=>item.publisherPublicAccountId&&accountIds.includes(item.publisherPublicAccountId));const ownedAppointments=appointmentRows.filter(item=>(item.inviterPublicAccountId&&accountIds.includes(item.inviterPublicAccountId))||(item.inviteePublicAccountId&&accountIds.includes(item.inviteePublicAccountId)));const eventIds=[...new Set([...ownedRegistrations.map(item=>item.eventId),...ownedPosts.map(item=>item.eventId),...ownedAppointments.map(item=>item.eventId)])];return{id:person.id,name:person.displayName,status:person.status,mergedInto:person.mergedIntoPersonId,identities:identities.filter(item=>accountIds.includes(item.accountId)).map(item=>`${item.identityType} · ${item.displayMasked}`),events:eventIds.map(id=>eventMap.get(id)??id),facts:{账号:ownedAccounts.length,身份:identities.filter(item=>accountIds.includes(item.accountId)).length,报名:ownedRegistrations.length,签到:checkins.filter(item=>recordIds.includes(item.recordId)).length,供需:ownedPosts.length,预约:ownedAppointments.length}};});
  const enterpriseItems=enterpriseRows.map(enterprise=>{const aliasIds=[enterprise.id,...enterpriseRows.filter(item=>item.mergedIntoEnterpriseId===enterprise.id).map(item=>item.id)];const ownedParticipations=participations.filter(item=>aliasIds.includes(item.enterpriseId));const exhibitorIds=ownedParticipations.map(item=>item.id);const ownedPosts=posts.filter(item=>item.publisherEnterpriseId&&aliasIds.includes(item.publisherEnterpriseId));const ownedAppointments=appointmentRows.filter(item=>(item.inviterEnterpriseId&&aliasIds.includes(item.inviterEnterpriseId))||(item.inviteeEnterpriseId&&aliasIds.includes(item.inviteeEnterpriseId)));const eventIds=[...new Set([...ownedParticipations.map(item=>item.eventId),...ownedPosts.map(item=>item.eventId),...ownedAppointments.map(item=>item.eventId)])];return{id:enterprise.id,name:enterprise.nameZh,status:enterprise.status,mergedInto:enterprise.mergedIntoEnterpriseId,aliases:enterpriseRows.filter(item=>item.mergedIntoEnterpriseId===enterprise.id).map(item=>item.nameZh),events:eventIds.map(id=>eventMap.get(id)??id),facts:{参展:ownedParticipations.length,产品:productRows.filter(item=>exhibitorIds.includes(item.eventExhibitorId)).length,询盘:inquiryRows.filter(item=>exhibitorIds.includes(item.eventExhibitorId)).length,供需:ownedPosts.length,预约:ownedAppointments.length}};});
  const[exportRequests,exportFiles,exportDownloads]=await Promise.all([db.select().from(sensitiveExportRequests),db.select().from(sensitiveExportFiles),db.select().from(sensitiveExportDownloadLogs)]);const now=new Date().toISOString();const exportItems=exportRequests.sort((a,b)=>b.requestedAt.localeCompare(a.requestedAt)).map(item=>{const file=exportFiles.find(candidate=>candidate.id===item.fileId);return{id:item.id,scope:item.scope,dataset:item.dataset,purpose:item.purpose,status:file&&file.expiresAt<=now?'EXPIRED':item.status,requestedByName:item.requestedByName,requestedAt:item.requestedAt,reviewedByName:item.reviewedByName,reviewedAt:item.reviewedAt,reviewReason:item.reviewReason,file:file?{fileName:file.fileName,rowCount:file.rowCount,sha256:file.sha256,generatedAt:file.generatedAt,expiresAt:file.expiresAt}:null,downloadCount:exportDownloads.filter(log=>log.requestId===item.id&&log.result==='SUCCESS').length};});
  const importJobs=(await db.select().from(dataImportJobs)).filter(item=>item.eventId===currentEventId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(item=>({id:item.id,sourceFileName:item.sourceFileName,sourceSha256:item.sourceSha256,status:item.status,rowCount:item.rowCount,validCount:item.validCount,errorCount:item.errorCount,requestedByName:item.requestedByName,validatedAt:item.validatedAt,committedAt:item.committedAt,committedByName:item.committedByName}));
  return <AdminShell active="/data-assets" title="集团数据资产" eyebrow="集团工作台 / 数据资产 / 主档治理"><DataAssetsWorkspace persons={personItems} enterprises={enterpriseItems} merges={merges.sort((a,b)=>b.mergedAt.localeCompare(a.mergedAt))}/><SensitiveExportPanel initialItems={exportItems} fieldOptions={sensitiveExportFieldOptions}/><DataImportPanel initialJobs={importJobs}/></AdminShell>;}
