import { desc, eq } from 'drizzle-orm';
import { AdminShell } from '@/components/admin-shell';
import { EnterpriseContactHandoffPanel } from '@/components/enterprise-contact-handoff-panel';
import { ExhibitorWorkspace } from '@/components/exhibitor-workspace';
import { getDb } from '@/db';
import { enterpriseAccounts, enterpriseContactHistory, enterpriseIdentities, enterprises, eventExhibitors, exhibitorProfileVersions, inquiries, products } from '@/db/schema';
import { getCurrentSessionActor } from '@/lib/auth';
import { getCurrentEventId } from '@/lib/current-event';

export default async function ExhibitorsPage() {
  const db = getDb();
  const eventId = await getCurrentEventId();
  const exhibitors = await db.select({ id: eventExhibitors.id, enterpriseId: enterprises.id, nameZh: enterprises.nameZh, nameIntl: enterprises.nameIntl, country: enterprises.country, industry: enterprises.industry, contactName: enterprises.contactName, contactEmailMasked: enterprises.contactEmailMasked, qualification: eventExhibitors.qualificationStatus, publish: eventExhibitors.publishStatus, category: eventExhibitors.category, description: eventExhibitors.description, currentVersionId: eventExhibitors.currentVersionId, productCount: eventExhibitors.productCount, boothNo: eventExhibitors.boothNo, source: eventExhibitors.source }).from(eventExhibitors).innerJoin(enterprises, eq(eventExhibitors.enterpriseId, enterprises.id)).where(eq(eventExhibitors.eventId, eventId));
  const profiles = await db.select().from(exhibitorProfileVersions).where(eq(exhibitorProfileVersions.eventId, eventId)).orderBy(desc(exhibitorProfileVersions.versionNo));
  const productRows = await db.select({ id: products.id, exhibitorId: products.eventExhibitorId, name: products.name, category: products.category, status: products.publishStatus, enterpriseName: enterprises.nameZh }).from(products).innerJoin(eventExhibitors, eq(products.eventExhibitorId, eventExhibitors.id)).innerJoin(enterprises, eq(eventExhibitors.enterpriseId, enterprises.id)).where(eq(products.eventId, eventId));
  const inquiryRows = await db.select({ id: inquiries.id, exhibitorId: inquiries.eventExhibitorId, enterpriseName: enterprises.nameZh, customerName: inquiries.customerName, contactMasked: inquiries.contactMasked, contactPrivate: inquiries.contactPrivate, content: inquiries.content, status: inquiries.status, createdAt: inquiries.createdAt, handledBy: inquiries.handledBy }).from(inquiries).innerJoin(eventExhibitors, eq(inquiries.eventExhibitorId, eventExhibitors.id)).innerJoin(enterprises, eq(eventExhibitors.enterpriseId, enterprises.id)).where(eq(inquiries.eventId, eventId)).orderBy(desc(inquiries.createdAt));
  const actor = await getCurrentSessionActor(); const canManageAccounts = actor?.groupRole === 'GROUP_ADMIN';
  const [accountRows, identityRows, historyRows] = canManageAccounts ? await Promise.all([db.select().from(enterpriseAccounts), db.select().from(enterpriseIdentities), db.select().from(enterpriseContactHistory).orderBy(desc(enterpriseContactHistory.createdAt))]) : [[], [], []];
  const accountGovernance = exhibitors.map((item) => { const account = accountRows.find((candidate) => candidate.enterpriseId === item.enterpriseId); if (!account) return null; return { eventExhibitorId: item.id, enterpriseName: item.nameZh, accountId: account.id, displayName: account.displayName, status: account.status, identities: identityRows.filter((identity) => identity.accountId === account.id).map((identity) => identity.displayMasked), histories: historyRows.filter((history) => history.accountId === account.id).map((history) => ({ id: history.id, oldIdentityMasked: history.oldIdentityMasked, newIdentityMasked: history.newIdentityMasked, oldDisplayName: history.oldDisplayName, newDisplayName: history.newDisplayName, reason: history.reason, operatorName: history.operatorName, verifiedAt: history.verifiedAt })) }; }).filter((item): item is NonNullable<typeof item> => Boolean(item));
  return <AdminShell active="/exhibitors" title="企业、产品与询盘管理"><ExhibitorWorkspace initialExhibitors={exhibitors.map((item) => ({ ...item, profiles: profiles.filter((profile) => profile.eventExhibitorId === item.id).map((profile) => ({ id: profile.id, versionNo: profile.versionNo, status: profile.reviewStatus })) }))} initialProducts={productRows} initialInquiries={inquiryRows} /><EnterpriseContactHandoffPanel accounts={accountGovernance} canManage={canManageAccounts}/></AdminShell>;
}
