import Link from 'next/link';
import type { CSSProperties, ReactNode } from 'react';
import { DEFAULT_PORTAL_SITE_PAGES, type PortalBlock, type PortalDocument } from '@/lib/portal-types';
import { languageMeta } from '@/lib/portal-localization';

function text(props: Record<string, unknown>, key: string, fallback = '') { return typeof props[key] === 'string' ? props[key] as string : fallback; }
function list<T>(props: Record<string, unknown>, key: string) { return Array.isArray(props[key]) ? props[key] as T[] : []; }
function aiBadge(props: Record<string, unknown>, key: string) { return list<string>(props, '__aiTranslatedFields').includes(key) ? <small className="ai-translation-badge">AI翻译</small> : null; }
const uiCopy: Record<string, Record<string, string>> = {
  en: { completeAgenda: 'Full programme', news: 'News', documents: 'Documents', matching: 'Business matching', company: 'Company workspace', login: 'Visitor login', related: 'Approved companies, products and business opportunities are published here.', allExhibitors: 'View all exhibitors', directory: 'Company and product directory', boothPending: 'Booth pending', coordinates: 'Coordinates', download: 'Download PDF', unavailable: 'No published file', back: 'Management', china: 'China', africa: 'Africa' },
  fr: { completeAgenda: 'Programme complet', news: 'Actualités', documents: 'Documents', matching: 'Rencontres B2B', company: 'Espace exposant', login: 'Connexion visiteurs', related: 'Les entreprises, produits et opportunités approuvés sont publiés ici.', allExhibitors: 'Voir tous les exposants', directory: 'Annuaire des entreprises et produits', boothPending: 'Stand à attribuer', coordinates: 'Coordonnées', download: 'Télécharger le PDF', unavailable: 'Aucun fichier publié', back: 'Administration', china: 'Chine', africa: 'Afrique' },
  ar: { completeAgenda: 'البرنامج الكامل', news: 'الأخبار', documents: 'الوثائق', matching: 'لقاءات الأعمال', company: 'مساحة العارض', login: 'دخول الزوار', related: 'تظهر هنا الشركات والمنتجات والفرص المعتمدة.', allExhibitors: 'جميع العارضين', directory: 'دليل الشركات والمنتجات', boothPending: 'الجناح قيد التخصيص', coordinates: 'الإحداثيات', download: 'تنزيل PDF', unavailable: 'لا يوجد ملف منشور', back: 'الإدارة', china: 'الصين', africa: 'أفريقيا' },
};
function ui(props: Record<string, unknown>, key: string, fallback: string) { return uiCopy[text(props, '_language', 'zh-CN')]?.[key] ?? fallback; }

const renderers: Record<PortalBlock['type'], (block: PortalBlock) => ReactNode> = {
  hero: ({ props }) => <section className="portal-hero"><div className="portal-hero-copy"><span className="demo-badge">ALPHA · 本地测试数据 · 组件生成页面</span><p className="portal-kicker">{text(props, 'kicker')}</p><h1>{text(props, 'title')}<br/><em>{text(props, 'accentTitle')}</em></h1><p>{text(props, 'description')} {aiBadge(props, 'description')}</p><div><a className="portal-primary button-link" href={text(props, 'primaryHref', '#contact')}>{text(props, 'primaryLabel', '立即报名')}</a><a href={text(props, 'secondaryHref', '#about')}>{text(props, 'secondaryLabel', '了解展会')} →</a></div></div><div className="portal-hero-art"><span>{ui(props, 'china', '中国')}</span><i>⇄</i><span>{ui(props, 'africa', '非洲')}</span><div>CASABLANCA<br/><strong>2026</strong></div></div></section>,
  intro: ({ id, props }) => <section id="about" data-block-id={id} className="portal-section intro-section"><div><span className="section-number">01</span><p className="portal-kicker">{text(props, 'kicker')}</p><h2>{text(props, 'title')}</h2></div><div><p>{text(props, 'body')} {aiBadge(props, 'body')}</p><dl>{list<{label:string;value:string}>(props, 'facts').map((item) => <div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl></div></section>,
  stats: ({ id, props }) => <section id="stats" data-block-id={id} className="portal-stats"><div><span className="portal-kicker">EVENT DATA</span><h2>{text(props, 'title', '展会数据')}</h2></div><dl>{list<{label:string;value:string}>(props, 'items').map((item) => <div key={item.label}><dt>{item.value}</dt><dd>{item.label}</dd></div>)}</dl></section>,
  agenda: ({ id, props }) => <section id="agenda" data-block-id={id} className="agenda-section"><div><span className="portal-kicker">{text(props, 'kicker')}</span><h2>{text(props, 'title')}</h2><p>{text(props, 'description')} {aiBadge(props, 'description')}</p></div><ol>{list<{day:string;time:string;title:string}>(props, 'items').map((item, index) => <li key={`${item.day}-${index}`}><time>{item.day}</time><strong>{item.title}</strong><span>{item.time}</span></li>)}</ol></section>,
  industries: ({ id, props }) => <section id="industries" data-block-id={id} className="industry-section"><div className="section-heading"><div><span className="portal-kicker">{text(props, 'kicker')}</span><h2>{text(props, 'title')}</h2></div></div><div className="industry-grid">{list<string>(props, 'items').map((item,index)=><article key={item}><span>{String(index+1).padStart(2,'0')}</span><h3>{item}</h3><p>{ui(props, 'related', '相关企业、产品和供需信息经审核后进入公开门户。')}</p></article>)}</div></section>,
  enterpriseList: ({ id, props }) => { const items = list<{name:string;country:string;booth:string;href?:string}>(props, 'items'); const visible = items.length ? items : [{name:'已审核企业数据',country:'发布后自动绑定',booth:'—'}]; return <section data-block-id={id} className="portal-enterprises"><div><span className="portal-kicker">{text(props, 'kicker')}</span><h2>{text(props, 'title')}</h2></div><div className="portal-enterprise-grid">{visible.map((item) => <Link href={item.href ?? '#contact'} key={`${item.name}-${item.booth}`}><strong>{item.name}</strong><span>{item.country} · {item.booth || ui(props, 'boothPending', '展位待分配')}</span></Link>)}<Link href={text(props, '_directoryHref', '/exhibition/2026-morocco/exhibitors')}><strong>{ui(props, 'allExhibitors', '查看全部参展企业')}</strong><span>{ui(props, 'directory', '企业与产品公开目录')} →</span></Link></div></section>; },
  map: ({ id, props }) => <section data-block-id={id} className="portal-map"><div><span className="portal-kicker">{text(props, 'kicker')}</span><h2>{text(props, 'title')}</h2><p>{text(props, 'address')}</p><small>{ui(props, 'coordinates', '坐标')}：{String(props.latitude ?? '')}, {String(props.longitude ?? '')}</small></div><div className="map-art"><i>●</i><span>CASABLANCA</span></div></section>,
  download: ({ id, props }) => <section data-block-id={id} className="portal-simple-block"><h2>{text(props, 'title', '资料下载')}</h2><p>{text(props, 'description')}</p>{text(props, 'href') ? <a className="portal-primary button-link" href={text(props, 'href')}>{ui(props, 'download', '下载 PDF')}</a> : <button disabled>{ui(props, 'unavailable', '暂无已发布文件')}</button>}</section>,
  contact: ({ id, props }) => <section id="contact" data-block-id={id} className="portal-cta"><div><span className="portal-kicker">{text(props, 'kicker')}</span><h2>{text(props, 'title')}</h2><p>{text(props, 'description')} {aiBadge(props, 'description')}</p></div><div><a className="portal-primary button-link" href={text(props, 'primaryHref', '/exhibition/2026-morocco/register/reg-main')}>{text(props, 'primaryLabel', '立即报名')} →</a><a className="button-link" href={text(props, 'secondaryHref', '#contact')}>{text(props, 'secondaryLabel', '申请参展')}</a></div></section>,
  html: ({ id, props }) => <section data-block-id={id} className="portal-simple-block"><h2>{text(props, 'title', '自定义内容')}</h2><p>{text(props, 'description', 'Alpha阶段只展示受控文本，正式HTML白名单将在安全评审后启用。')}</p></section>,
};

export function PortalRenderer({ document, eventName, eventSlug = '2026-morocco', compact = false, publicAccountName, currentLanguage = document.language || 'zh-CN', availableLanguages = ['zh-CN', 'en', 'fr'] }: { document: PortalDocument; eventName: string; eventSlug?: string; compact?: boolean; publicAccountName?: string | null; currentLanguage?: string; availableLanguages?: string[] }) {
  const style = { '--portal-green': document.theme.primary, '--coral': document.theme.accent, '--portal-surface': document.theme.surface } as CSSProperties;
  const heroTitle = document.blocks.find((block) => block.type === 'hero')?.props.title;
  const localizedEventName = currentLanguage === 'zh-CN' || typeof heroTitle !== 'string' ? eventName : heroTitle;
  const sitePages = document.sitePages ?? DEFAULT_PORTAL_SITE_PAGES;
  const languageLinks = availableLanguages.filter((language) => languageMeta[language]).map((language) => <Link className={language === currentLanguage ? 'active' : ''} href={`/exhibition/${eventSlug}${language === 'zh-CN' ? '' : `?lang=${language}`}`} key={language}>{languageMeta[language].short}</Link>);
  return <main className={`public-portal ${compact ? 'builder-portal-render' : ''}`} style={style} lang={currentLanguage} dir={document.direction ?? languageMeta[currentLanguage]?.direction ?? 'ltr'}>
    <header className="portal-header"><div className="portal-logo"><span>CA</span><div><strong>{localizedEventName}</strong><small>CHINA–AFRICA ECONOMIC AND TRADE EXPO</small></div></div><nav>{document.nav.filter(item => item.visible).map(item => <a key={item.id} href={`#${item.anchor}`}>{item.label}</a>)}{sitePages.filter(item => item.visible).map(item => <Link key={item.id} href={`/exhibition/${eventSlug}${item.path}`}>{item.label}</Link>)}</nav>{compact?<div className="portal-language-links">{languageLinks}</div>:<div className="portal-account-links"><span className="portal-language-links">{languageLinks}</span><Link href="/company-workspace/login">{uiCopy[currentLanguage]?.company ?? '企业工作台'}</Link><Link href={publicAccountName?`/exhibition/${eventSlug}/me`:`/exhibition/${eventSlug}/login`}>{publicAccountName??uiCopy[currentLanguage]?.login??'观众登录'}</Link></div>}</header>
    <section className="portal-page-hub" aria-label="展会服务子页面"><div><span>EXHIBITION SERVICES</span><h2>展会服务导航</h2><p>各栏目使用独立路径，并读取后台对应模块中已审核发布的数据。</p></div><nav>{sitePages.filter(item => item.visible).map(item => <Link key={item.id} href={`/exhibition/${eventSlug}${item.path}`}><strong>{item.label}</strong><small>{item.description}</small><b>进入栏目 →</b></Link>)}</nav></section>
    {document.blocks.filter(block => block.visible).map(block => { const contextualBlock = { ...block, props: { ...block.props, _language: currentLanguage, ...(block.type === 'enterpriseList' ? { _directoryHref: `/exhibition/${eventSlug}/exhibitors` } : {}) } }; return <div className="portal-render-block" data-component={block.type} key={block.id}>{renderers[block.type]?.(contextualBlock)}</div>; })}
    <footer className="portal-footer"><div className="portal-logo"><span>CA</span><div><strong>{localizedEventName}</strong><small>ALPHA PORTAL</small></div></div><p>页面结构与内容来自已发布门户版本。{document.translation?.generatedByAi ? ' 小语种长文本保留AI翻译来源标识。' : ''}</p><Link href="/">{uiCopy[currentLanguage]?.back ?? '返回管理后台'}</Link></footer>
  </main>;
}
