'use client';
import { FormEvent, useRef, useState } from 'react';

type ActiveCheckin = { id: string; scope: string; activityId: string | null; method: string; operatorName: string; occurredAt: string };
type Result = { id: string; personName: string; organization: string; mobileMasked: string; emailMasked: string; status: string; activityId: string; activityName: string; accessCode: string; activeCheckins: ActiveCheckin[] };
type Recent = { id: string; personName: string; organization: string; scope: string; method: string; operatorName: string; occurredAt: string; reversed: boolean };

export function CheckinConsole({ eventId, eventName, activityId, activityName, initialRecent, canReverse }: { eventId: string; eventName: string; activityId: string; activityName: string; initialRecent: Recent[]; canReverse: boolean }) {
  const [query, setQuery] = useState(''); const [scope, setScope] = useState<'EVENT' | 'ACTIVITY'>('ACTIVITY'); const [results, setResults] = useState<Result[]>([]); const [recent, setRecent] = useState(initialRecent); const [message, setMessage] = useState('扫描二维码，或按姓名、手机、邮箱、单位、凭证码查询。'); const [cameraOpen, setCameraOpen] = useState(false); const [reasons, setReasons] = useState<Record<string, string>>({}); const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null);
  async function search(value = query) { if (!value.trim()) return setMessage('请输入查询条件或扫描凭证码'); const response = await fetch(`/api/checkin/lookup?eventId=${encodeURIComponent(eventId)}&query=${encodeURIComponent(value.trim())}`); const data = await response.json() as { error?: string; results?: Result[] }; if (!response.ok) return setMessage(data.error ?? '查询失败'); setResults(data.results ?? []); setMessage(data.results?.length ? `找到 ${data.results.length} 条匹配记录。` : '没有找到匹配的报名记录。'); }
  async function submit(event: FormEvent) { event.preventDefault(); await search(); }
  async function execute(record: Result, method: 'STAFF_SCAN' | 'MANUAL_SEARCH' = 'MANUAL_SEARCH') { const response = await fetch('/api/checkin/execute', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ recordId: record.id, scope, activityId: scope === 'ACTIVITY' ? activityId : undefined, method, requestKey: `console-${crypto.randomUUID()}` }) }); const data = await response.json() as { error?: string; id?: string; occurredAt?: string; checkedInAt?: string }; if (!response.ok) return setMessage(`${data.error ?? '签到失败'}${data.checkedInAt ? `：${data.checkedInAt.slice(0, 19).replace('T', ' ')}` : ''}`); const now = data.occurredAt!; const active = { id: data.id!, scope, activityId: scope === 'ACTIVITY' ? activityId : null, method, operatorName: '当前员工', occurredAt: now }; setResults(current => current.map(item => item.id === record.id ? { ...item, status: 'CHECKED_IN', activeCheckins: [...item.activeCheckins, active] } : item)); setRecent(current => [{ ...active, personName: record.personName, organization: record.organization, reversed: false }, ...current]); setMessage(`${record.personName}已完成${scope === 'EVENT' ? '展会级' : '活动级'}签到。`); }
  async function reverse(item: Recent) { const reason = reasons[item.id]?.trim(); if (!reason) return setMessage('撤销误签到必须填写原因'); const response = await fetch(`/api/checkin/${item.id}/reverse`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ reason }) }); const data = await response.json() as { error?: string }; if (!response.ok) return setMessage(data.error ?? '撤销失败'); setRecent(current => current.map(row => row.id === item.id ? { ...row, reversed: true } : row)); setResults(current => current.map(result => ({ ...result, activeCheckins: result.activeCheckins.filter(log => log.id !== item.id) }))); setMessage(`${item.personName}的误签到已撤销，原流水继续保留。`); }
  function stopCamera() { streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; setCameraOpen(false); }
  async function startCamera() { const Detector = (window as unknown as { BarcodeDetector?: new (options: { formats: string[] }) => { detect(source: HTMLVideoElement): Promise<Array<{ rawValue: string }>> } }).BarcodeDetector; if (!Detector || !navigator.mediaDevices?.getUserMedia) return setMessage('当前浏览器不支持摄像头二维码识别，可使用系统相机复制凭证码或连接扫码枪。'); try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } }); streamRef.current = stream; setCameraOpen(true); setTimeout(async () => { if (!videoRef.current) return; videoRef.current.srcObject = stream; await videoRef.current.play(); const detector = new Detector({ formats: ['qr_code'] }); for (let index = 0; index < 120 && streamRef.current; index += 1) { const found = await detector.detect(videoRef.current); if (found[0]?.rawValue) { setQuery(found[0].rawValue); stopCamera(); await search(found[0].rawValue); return; } await new Promise(resolve => setTimeout(resolve, 250)); } }, 50); } catch { stopCamera(); setMessage('无法使用摄像头，请检查权限或改用凭证码搜索。'); } }
  return <><section className="checkin-hero"><div><span>ONSITE CHECK-IN · ONLINE</span><h1>现场签到台</h1><p>{eventName} · 默认只签到，无签退和重复进出统计。</p></div><div><strong>{activityName}</strong><span>支持展会级 / 活动级独立签到</span></div></section><section className="checkin-console-panel"><form onSubmit={submit}><label>人员或凭证查询<input aria-label="人员或凭证查询" value={query} onChange={event => setQuery(event.target.value)} placeholder="姓名 / 手机 / 邮箱 / 单位 / EXPO凭证码"/></label><label>签到层级<select aria-label="签到层级" value={scope} onChange={event => setScope(event.target.value as 'EVENT' | 'ACTIVITY')}><option value="ACTIVITY">活动级 · {activityName}</option><option value="EVENT">展会级 · 整届展会</option></select></label><button className="primary-button">查询</button><button type="button" onClick={cameraOpen ? stopCamera : startCamera}>{cameraOpen ? '关闭摄像头' : '摄像头扫码'}</button></form>{cameraOpen ? <video className="checkin-camera" ref={videoRef} muted playsInline/> : null}<p role="status">{message}</p><div className="checkin-search-results">{results.map(result => <article key={result.id}><div><span>{result.activityName} · {result.accessCode}</span><h2>{result.personName}</h2><p>{result.organization} · {result.mobileMasked} {result.emailMasked}</p><small>{result.activeCheckins.length ? result.activeCheckins.map(item => `${item.scope === 'EVENT' ? '展会级' : '活动级'} ${item.occurredAt.slice(11, 16)}`).join(' · ') : '尚未签到'}</small></div><button className="primary-button" onClick={() => execute(result, query.startsWith('EXPO-') ? 'STAFF_SCAN' : 'MANUAL_SEARCH')}>执行{scope === 'EVENT' ? '展会级' : '活动级'}签到</button></article>)}</div></section><section className="checkin-recent"><header><div><span>RECENT RECORDS</span><h2>最近签到与撤销</h2></div><small>在线模式 · 原流水不删除</small></header>{recent.map(item => <article key={item.id}><div><strong>{item.personName}</strong><span>{item.organization} · {item.scope === 'EVENT' ? '展会级' : '活动级'} · {item.method}</span></div><time>{item.occurredAt.slice(0, 19).replace('T', ' ')}</time><b>{item.reversed ? '已撤销' : '有效'}</b>{canReverse && !item.reversed ? <div><input aria-label={`${item.personName}撤销原因`} value={reasons[item.id] ?? ''} onChange={event => setReasons(current => ({ ...current, [item.id]: event.target.value }))} placeholder="误签到原因"/><button onClick={() => reverse(item)}>撤销</button></div> : null}</article>)}</section><section className="checkin-planned"><strong>证件与离线签到</strong><p>证件模板、打印、补打、闸机和离线同步继续保持待定入口；当前二维码仅作为在线签到凭证。</p></section></>;
}
