'use client';
import { useMemo, useState } from 'react';

type MasterItem={id:string;name:string;status:string;mergedInto:string|null;identities?:string[];aliases?:string[];events:string[];facts:Record<string,number>};
type MergeItem={id:string;entityType:string;sourceId:string;targetId:string;status:string;mergedBy:string;mergedAt:string;revertedBy:string|null;revertedAt:string|null};
type Preview={entityType:string;source:{id:string;name:string;facts:Record<string,unknown>};target:{id:string;name:string;facts:Record<string,unknown>};strategy:Record<string,string>};

export function DataAssetsWorkspace({persons,enterprises,merges}:{persons:MasterItem[];enterprises:MasterItem[];merges:MergeItem[]}){
  const[tab,setTab]=useState<'PERSON'|'ENTERPRISE'>('PERSON');const[query,setQuery]=useState('');const[message,setMessage]=useState('系统不会根据姓名、单位或相似度自动合并。');const[preview,setPreview]=useState<Preview|null>(null);const[reason,setReason]=useState('经人工核对为同一主体');const[undoReason,setUndoReason]=useState('访谈复核后确认应保持独立');
  const items=tab==='PERSON'?persons:enterprises;const active=items.filter(item=>item.status!=='MERGED');const[sourceId,setSourceId]=useState('');const[targetId,setTargetId]=useState('');
  const visible=useMemo(()=>items.filter(item=>`${item.name} ${item.id} ${(item.aliases??[]).join(' ')} ${(item.identities??[]).join(' ')}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  function changeTab(value:'PERSON'|'ENTERPRISE'){setTab(value);setSourceId('');setTargetId('');setPreview(null);}
  async function loadPreview(){const response=await fetch('/api/data-assets/merge-preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entityType:tab,sourceId,targetId})});const result=await response.json() as Preview&{error?:string};if(!response.ok){setPreview(null);return setMessage(result.error??'预览失败');}setPreview(result);setMessage('预览只汇总归属变化，展会事实ID不会改写。');}
  async function merge(){if(!preview)return setMessage('请先生成并核对合并预览');const response=await fetch('/api/data-assets/merge',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entityType:tab,sourceId,targetId,reason})});const result=await response.json() as {error?:string};if(!response.ok)return setMessage(result.error??'合并失败');location.reload();}
  async function unmerge(id:string){const response=await fetch(`/api/data-assets/merges/${id}/unmerge`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reason:undoReason})});const result=await response.json() as {error?:string};if(!response.ok)return setMessage(result.error??'撤销失败');location.reload();}
  return <>
    <section className="data-asset-summary"><article><span>人员主档</span><strong>{persons.filter(item=>item.status!=='MERGED').length}</strong><small>按已验证身份跨届归集</small></article><article><span>企业主档</span><strong>{enterprises.filter(item=>item.status!=='MERGED').length}</strong><small>参展事实继续按届保留</small></article><article><span>有效合并</span><strong>{merges.filter(item=>item.status==='ACTIVE').length}</strong><small>全部可追踪并可撤销</small></article></section>
    <section className="data-asset-tabs"><button className={tab==='PERSON'?'active':''} onClick={()=>changeTab('PERSON')}>人员主档</button><button className={tab==='ENTERPRISE'?'active':''} onClick={()=>changeTab('ENTERPRISE')}>企业主档</button><input aria-label="搜索主档" value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索名称、身份或ID"/></section>
    <p className="data-asset-message" role="status">{message}</p>
    <section className="data-asset-layout"><div className="data-master-list">{visible.map(item=><article key={item.id} className={item.status==='MERGED'?'merged-record':''}><header><div><span>{item.status==='MERGED'?'已并入主记录':'集团主档'}</span><h2>{item.name}</h2><small>{item.id}</small></div><strong>{item.status}</strong></header>{item.identities?.length?<p>{item.identities.join('　')}</p>:null}{item.aliases?.length?<p>别名/从记录：{item.aliases.join('、')}</p>:null}<dl>{Object.entries(item.facts).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><footer>{item.events.length?item.events.join('；'):'暂无展会事实'}{item.mergedInto?<small> → {item.mergedInto}</small>:null}</footer></article>)}</div>
      <aside className="merge-console"><span>MANUAL MERGE</span><h2>人工合并与撤销</h2><p>主记录保留展示字段；从记录的账号归属或别名关系并入主记录。报名、签到、参展、产品、供需和预约原始ID保持不变。</p><label>从记录<select value={sourceId} onChange={event=>{setSourceId(event.target.value);setPreview(null);}}><option value="">请选择</option>{active.map(item=><option key={item.id} value={item.id}>{item.name} · {item.id.slice(-8)}</option>)}</select></label><label>主记录<select value={targetId} onChange={event=>{setTargetId(event.target.value);setPreview(null);}}><option value="">请选择</option>{active.filter(item=>item.id!==sourceId).map(item=><option key={item.id} value={item.id}>{item.name} · {item.id.slice(-8)}</option>)}</select></label><label>合并原因<input value={reason} onChange={event=>setReason(event.target.value)}/></label><button onClick={loadPreview} disabled={!sourceId||!targetId}>生成合并预览</button>{preview?<section className="merge-preview"><strong>{preview.source.name} → {preview.target.name}</strong><div><pre>{JSON.stringify(preview.source.facts,null,2)}</pre><span>归入</span><pre>{JSON.stringify(preview.target.facts,null,2)}</pre></div><small>策略：{Object.entries(preview.strategy).map(([key,value])=>`${key}=${value}`).join('；')}</small><button className="primary-button" onClick={merge}>确认人工合并</button></section>:null}<hr/><label>撤销原因<input value={undoReason} onChange={event=>setUndoReason(event.target.value)}/></label><div className="merge-history">{merges.map(item=><article key={item.id}><div><strong>{item.entityType} · {item.status}</strong><small>{item.sourceId.slice(-8)} → {item.targetId.slice(-8)}</small><span>{item.mergedBy} · {item.mergedAt.slice(0,16).replace('T',' ')}</span></div>{item.status==='ACTIVE'?<button onClick={()=>unmerge(item.id)}>撤销合并</button>:<small>{item.revertedBy} 已撤销</small>}</article>)}</div></aside>
    </section>
  </>;
}
