'use client';
import Link from 'next/link';
import { FormEvent, useMemo, useState } from 'react';
import { NotificationCenter, NotificationItem } from '@/components/notification-center';

type Profile = { id: string; versionNo: number; status: string; data: Record<string, unknown> };
type Product = { id: string; name: string; category: string; publishStatus: string; current: { id: string; versionNo: number; data: Record<string, unknown> } | null; pending: { id: string; versionNo: number; data: Record<string, unknown> } | null };
type Inquiry = { id: string; customerName: string; contactPrivate: string; content: string; status: string; createdAt: string; handledBy: string | null };
type CompanyPost = { id: string; publisherName: string; publisherEnterpriseId: string | null; postType: string; title: string; category: string; countriesJson: string; description: string; reviewStatus: string; createdAt: string };
type CompanyAppointment = { id: string; inviterName: string; inviteeName: string; inviterEnterpriseId: string | null; inviteeEnterpriseId: string | null; proposedStart: string; proposedEnd: string; locationPreference: string; confirmedStart: string | null; confirmedEnd: string | null; status: string; direction: string; responses: Array<{ id: string; action: string; responderName: string; createdAt: string }> };
export type EnterpriseParticipation = { id: string; eventId: string; eventName: string; shortName: string; slug: string; year: number; eventStatus: string; venueText: string; startAt: string; endAt: string; qualificationStatus: string; publishStatus: string; boothNo: string | null; category: string; applicationIntent: string; matchingEnabled: boolean; currentProfile: Profile | null; pendingProfile: Profile | null; products: Product[]; inquiries: Inquiry[]; posts: CompanyPost[]; marketPosts: CompanyPost[]; counterparties: Array<{ id: string; name: string }>; appointments: CompanyAppointment[] };
export type EnterpriseApplicationEvent = { id: string; name: string; shortName: string; year: number; city: string; country: string; startAt: string };
const statusText: Record<string, string> = { APPROVED: '资格通过', PENDING: '待审核', REJECTED: '已退回', PUBLISHED: '已公开', DRAFT: '草稿', RETURNED: '已退回', ARCHIVED: '已归档', PREPARING: '筹备中', NEW: '待联系', CONTACTED: '已联系', CLOSED: '已关闭', PROPOSED: '待回应', COUNTERED: '建议新时间', ACCEPTED: '已接受', CANCELED: '已取消' };

export function EnterpriseWorkspaceClient({ enterpriseName, displayName, identityText, participations, applicationEvents, notifications }: { enterpriseName: string; displayName: string; identityText: string; participations: EnterpriseParticipation[]; applicationEvents: EnterpriseApplicationEvent[]; notifications: NotificationItem[] }) {
  const [selectedId, setSelectedId] = useState(participations[0]?.id ?? '');
  const [tab, setTab] = useState<'overview' | 'profile' | 'products' | 'inquiries' | 'planned' | 'notifications'>('overview');
  const [showApplication, setShowApplication] = useState(!participations.length);
  const [message, setMessage] = useState('每届资料独立保存；新版本审核期间，公开门户继续展示上一已发布版本。');
  const selected = useMemo(() => participations.find(item => item.id === selectedId) ?? participations[0], [participations, selectedId]);
  const qualificationApproved = selected?.qualificationStatus === 'APPROVED';

  return <>
    <section className="company-mobile-notice"><strong>企业工作台一期以PC为主</strong><p>当前手机端只提供展会、审核和展位摘要。请使用电脑维护企业资料与产品。</p></section>
    <section className="company-application-bar"><div><span>参展申请</span><strong>{applicationEvents.length ? `${applicationEvents.length} 个展会可申请` : '当前无可申请展会'}</strong></div><button disabled={!applicationEvents.length} onClick={() => setShowApplication(value => !value)}>{showApplication ? '收起申请表' : '申请参加新展会'}</button></section>
    {showApplication && applicationEvents.length ? <ApplicationForm events={applicationEvents} onMessage={setMessage}/> : null}
    {!selected ? <section className="company-empty"><h2>暂无参展记录</h2><p>请从上方选择开放中的展会提交企业参展申请。</p></section> : <>
      <section className="company-summary"><div><span>企业账号</span><strong>{enterpriseName}</strong><small>{displayName} · {identityText}</small></div><div><span>历届参展</span><strong>{participations.length}</strong><small>跨届可查，资料互相隔离</small></div><div><span>当前资格</span><strong>{statusText[selected.qualificationStatus] ?? selected.qualificationStatus}</strong><small>{selected.shortName}</small></div><div><span>展位</span><strong>{selected.boothNo ?? '待分配'}</strong><small>由工作人员后台分配</small></div></section>
      <section className="company-event-switch"><label>选择参展届次<select value={selected.id} onChange={event => { setSelectedId(event.target.value); setTab('overview'); }}>{participations.map(item => <option key={item.id} value={item.id}>{item.year} · {item.shortName} · {statusText[item.qualificationStatus] ?? item.qualificationStatus}</option>)}</select></label><div><strong>{selected.eventName}</strong><span>{selected.venueText || '场地待公布'} · 展位 {selected.boothNo ?? '待分配'}</span></div><Link href={`/exhibition/${selected.slug}`}>查看公开门户 ↗</Link></section>
      <nav className="company-tabs"><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}>工作台首页</button><button disabled={!qualificationApproved} className={tab === 'profile' ? 'active' : ''} onClick={() => setTab('profile')}>本届企业资料</button><button disabled={!qualificationApproved} className={tab === 'products' ? 'active' : ''} onClick={() => setTab('products')}>本届产品</button><button disabled={!qualificationApproved} className={tab === 'inquiries' ? 'active' : ''} onClick={() => setTab('inquiries')}>询盘</button><button disabled={!qualificationApproved} className={tab === 'planned' ? 'active' : ''} onClick={() => setTab('planned')}>供需与预约</button><button className={tab === 'notifications' ? 'active' : ''} onClick={() => setTab('notifications')}>通知 {notifications.filter((item) => item.status === 'UNREAD').length ? `(${notifications.filter((item) => item.status === 'UNREAD').length})` : ''}</button></nav>
      <p className="company-message" role="status">{message}</p>
      <section className="company-desktop-editor">
        {tab === 'overview' ? <CompanyOverview item={selected}/> : null}
        {tab === 'profile' && qualificationApproved ? <ProfileEditor key={selected.id} item={selected} onMessage={setMessage}/> : null}
        {tab === 'products' && qualificationApproved ? <ProductEditor key={selected.id} item={selected} onMessage={setMessage}/> : null}
        {tab === 'inquiries' && qualificationApproved ? <InquiryList item={selected} onMessage={setMessage}/> : null}
        {tab === 'planned' && qualificationApproved ? <EnterpriseMatchingPanel item={selected} onMessage={setMessage}/> : null}
        {tab === 'notifications' ? <NotificationCenter initialItems={notifications} endpointPrefix="/api/company-workspace/notifications"/> : null}
      </section>
    </>}
  </>;
}

function ApplicationForm({ events, onMessage }: { events: EnterpriseApplicationEvent[]; onMessage: (value: string) => void }) {
  const [form, setForm] = useState({ eventId: events[0]?.id ?? '', category: '', intent: '' });
  const [submitting, setSubmitting] = useState(false);
  async function submit(event: FormEvent) {
    event.preventDefault(); setSubmitting(true); onMessage('正在提交参展申请…');
    const response = await fetch('/api/company-workspace/applications', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) });
    const result = await response.json() as { error?: string };
    setSubmitting(false); if (!response.ok) return onMessage(result.error ?? '参展申请提交失败');
    onMessage('参展申请已提交，资格审核通过后解锁本届企业资料和产品。'); setTimeout(() => location.reload(), 650);
  }
  const selected = events.find(item => item.id === form.eventId);
  return <form className="company-panel company-application-form" onSubmit={submit}><div><span>NEW PARTICIPATION</span><h2>企业参展申请</h2><p>每届申请形成独立参展记录，不复用往届资料和产品。</p></div><label>申请展会<select required value={form.eventId} onChange={event => setForm({ ...form, eventId: event.target.value })}>{events.map(item => <option key={item.id} value={item.id}>{item.year} · {item.shortName} · {item.city}</option>)}</select></label><label>参展分类<input required value={form.category} onChange={event => setForm({ ...form, category: event.target.value })} placeholder="如：技术装备"/></label><label className="wide">参展诉求<textarea required value={form.intent} onChange={event => setForm({ ...form, intent: event.target.value })} placeholder="说明展品方向、合作目标和现场需求"/></label><small>{selected ? `${selected.country} · ${selected.startAt.slice(0, 10)}` : ''}</small><button className="primary-button" disabled={submitting}>{submitting ? '正在提交…' : '提交资格审核'}</button></form>;
}

function EnterpriseMatchingPanel({ item, onMessage }: { item: EnterpriseParticipation; onMessage: (value: string) => void }) {
  const [post, setPost] = useState({ postType: 'DEMAND', title: '', category: item.category, countries: '摩洛哥', description: '' });
  const [appointment, setAppointment] = useState({ inviteeEnterpriseId: item.counterparties[0]?.id ?? '', sourcePostId: '', proposedStart: item.startAt.slice(0, 16), proposedEnd: `${item.startAt.slice(0, 11)}10:00`, locationPreference: '现场洽谈区' });
  if (!item.matchingEnabled) return <section className="company-panel planned-panel"><span>本届功能关闭</span><h2>供需发布与线下预约</h2><p>工作人员尚未为本届展会开启该功能。AI配对、在线视频和意向金额继续保持待定。</p></section>;
  async function createPost(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/company-workspace/exhibitors/${item.id}/matching-posts`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...post, countries: post.countries.split(/[,，]/).map(value => value.trim()).filter(Boolean) }) }); const result = await response.json() as { error?: string }; if (!response.ok) return onMessage(result.error ?? '供需提交失败'); onMessage('供需信息已提交，另一员工审核后进入企业市场。'); setTimeout(() => location.reload(), 650); }
  async function createAppointment(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/company-workspace/exhibitors/${item.id}/appointments`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(appointment) }); const result = await response.json() as { error?: string }; if (!response.ok) return onMessage(result.error ?? '预约创建失败'); onMessage('线下预约已发出，等待对方企业响应；当前不占正式时段。'); setTimeout(() => location.reload(), 650); }
  async function respond(id: string, action: 'ACCEPT' | 'REJECT' | 'CANCEL') { const response = await fetch(`/api/company-workspace/appointments/${id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action }) }); const result = await response.json() as { error?: string; conflicts?: Array<{ reason: string }> }; if (!response.ok) return onMessage(result.conflicts?.map(value => value.reason).join('；') || result.error || '预约处理失败'); onMessage(action === 'ACCEPT' ? '预约已接受并通过时间冲突检查。' : action === 'REJECT' ? '预约已拒绝。' : '预约已取消。'); setTimeout(() => location.reload(), 500); }
  function bindPost(postId: string) { const target = item.marketPosts.find(value => value.id === postId); setAppointment(current => ({ ...current, sourcePostId: postId, inviteeEnterpriseId: target?.publisherEnterpriseId ?? current.inviteeEnterpriseId })); }
  function applyTimeSlot(value: string) { if (!value) return; const [start, end] = value.split('|'); setAppointment(current => ({ ...current, proposedStart: start, proposedEnd: end })); }
  return <section className="enterprise-matching-layout">
    <form className="company-panel company-form" onSubmit={createPost}><div><span>SUPPLY & DEMAND</span><h2>发布本届供需</h2><p>审核通过后向本届参展企业展示。</p></div><label>类型<select value={post.postType} onChange={event => setPost({ ...post, postType: event.target.value })}><option value="DEMAND">采购需求</option><option value="SUPPLY">供应能力</option><option value="COOPERATION">合作</option><option value="INVESTMENT">投资</option></select></label><label>分类<input required value={post.category} onChange={event => setPost({ ...post, category: event.target.value })}/></label><label>目标国家<input value={post.countries} onChange={event => setPost({ ...post, countries: event.target.value })}/></label><label className="wide">标题<input required value={post.title} onChange={event => setPost({ ...post, title: event.target.value })}/></label><label className="wide">详细说明<textarea required value={post.description} onChange={event => setPost({ ...post, description: event.target.value })}/></label><button className="primary-button">提交供需审核</button></form>
    <form className="company-panel company-form" onSubmit={createAppointment}><div><span>OFFLINE APPOINTMENT</span><h2>发起线下面谈</h2><p>对方接受后才占用正式时段。</p></div><label>关联已发布供需<select value={appointment.sourcePostId} onChange={event => bindPost(event.target.value)}><option value="">不关联</option>{item.marketPosts.filter(value => value.publisherEnterpriseId).map(value => <option key={value.id} value={value.id}>{value.publisherName} · {value.title}</option>)}</select></label><label>被邀请企业<select required value={appointment.inviteeEnterpriseId} onChange={event => setAppointment({ ...appointment, inviteeEnterpriseId: event.target.value, sourcePostId: '' })}><option value="">请选择</option>{item.counterparties.map(value => <option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label className="wide">快速时间段<select defaultValue="" onChange={event => applyTimeSlot(event.target.value)}><option value="">手动填写或选择</option><option value={`${item.startAt.slice(0, 10)}T09:00|${item.startAt.slice(0, 10)}T10:00`}>首日 09:00—10:00</option><option value={`${item.startAt.slice(0, 10)}T10:30|${item.startAt.slice(0, 10)}T11:30`}>首日 10:30—11:30</option><option value={`${item.startAt.slice(0, 10)}T14:00|${item.startAt.slice(0, 10)}T15:00`}>首日 14:00—15:00</option></select></label><label>候选开始<input required type="datetime-local" value={appointment.proposedStart} onChange={event => setAppointment({ ...appointment, proposedStart: event.target.value })}/></label><label>候选结束<input required type="datetime-local" value={appointment.proposedEnd} onChange={event => setAppointment({ ...appointment, proposedEnd: event.target.value })}/></label><label className="wide">地点偏好<input value={appointment.locationPreference} onChange={event => setAppointment({ ...appointment, locationPreference: event.target.value })}/></label><button className="primary-button" disabled={!item.counterparties.length}>发起预约</button></form>
    <section className="company-panel enterprise-market"><div><span>我的发布</span><h2>本届供需状态</h2></div>{item.posts.length ? item.posts.map(value => <article key={value.id}><div><strong>{value.title}</strong><small>{value.category} · {value.publisherName}</small><p>{value.description}</p></div><span className={`state-pill ${value.reviewStatus.toLowerCase()}`}>{statusText[value.reviewStatus] ?? value.reviewStatus}</span></article>) : <p>尚未提交本届供需。</p>}</section>
    <section className="company-panel enterprise-market"><div><span>本届企业市场</span><h2>已发布供需</h2></div>{item.marketPosts.length ? item.marketPosts.map(value => <article key={value.id}><div><strong>{value.title}</strong><small>{value.publisherName} · {value.category}</small><p>{value.description}</p></div>{value.publisherEnterpriseId?<button onClick={() => bindPost(value.id)}>选为预约来源</button>:<small>公众发布 · 等待发布方发起预约</small>}</article>) : <p>其他发布方暂无已发布供需。</p>}</section>
    <section className="company-panel enterprise-appointment-list"><div><span>APPOINTMENTS</span><h2>我的线下预约</h2></div>{item.appointments.length ? item.appointments.map(value => <article key={value.id}><div><strong>{value.inviterName} ⇄ {value.inviteeName}</strong><small>{value.proposedStart.replace('T', ' ')}—{value.proposedEnd.slice(11)} · {value.locationPreference}</small></div><span className={`state-pill ${value.status.toLowerCase()}`}>{statusText[value.status] ?? value.status}</span><div>{value.direction === 'INCOMING' && ['PROPOSED', 'COUNTERED'].includes(value.status) ? <><button onClick={() => respond(value.id, 'REJECT')}>拒绝</button><button className="primary-button" onClick={() => respond(value.id, 'ACCEPT')}>接受</button></> : null}{((value.direction === 'OUTGOING' && ['PROPOSED', 'COUNTERED', 'ACCEPTED'].includes(value.status)) || value.status === 'ACCEPTED') ? <button onClick={() => respond(value.id, 'CANCEL')}>取消</button> : null}</div></article>) : <p>本届暂无企业预约。</p>}</section>
    <section className="company-panel planned-panel"><span>保持待定</span><h2>AI配对与意向金额</h2><p>本切片只覆盖人工供需筛选和线下时间预约。AI推荐、意向金额及在线视频不进入当前业务结论。</p></section>
  </section>;
}

function CompanyOverview({ item }: { item: EnterpriseParticipation }) { return <div className="company-grid"><article className="company-panel"><span>参展状态</span><h2>{statusText[item.qualificationStatus]} / {statusText[item.publishStatus]}</h2><p>{item.qualificationStatus === 'APPROVED' ? '资格与公开资料分别审核。资格通过不会自动发布企业资料。' : <>参展诉求：{item.applicationIntent || '未填写'}<br/>资格通过后解锁本届资料和产品。</>}</p></article><article className="company-panel"><span>资料版本</span><h2>{item.pendingProfile ? `V${item.pendingProfile.versionNo} 审核中` : item.currentProfile ? `V${item.currentProfile.versionNo} 已发布` : '尚未发布'}</h2><p>{item.qualificationStatus !== 'APPROVED' ? '当前因资格状态锁定。' : item.pendingProfile && item.currentProfile ? `公开端继续显示 V${item.currentProfile.versionNo}` : '审核通过后进入门户企业目录。'}</p></article><article className="company-panel"><span>产品与询盘</span><h2>{item.products.length} 项产品 · {item.inquiries.filter(row => row.status === 'NEW').length} 条新询盘</h2><p>产品逐项审核；询盘完整联系方式仅企业账号和有权限员工可见。</p></article><article className="company-panel"><span>资料下载</span><h2>平面图与参会资料</h2><p><Link href={`/exhibition/${item.slug}/documents`}>打开本届资料中心 →</Link></p></article></div>; }

function ProfileEditor({ item, onMessage }: { item: EnterpriseParticipation; onMessage: (value: string) => void }) {
  const source = item.pendingProfile?.data ?? item.currentProfile?.data ?? {}; const [form, setForm] = useState({ nameZh: String(source.nameZh ?? ''), nameIntl: String(source.nameIntl ?? ''), country: String(source.country ?? ''), category: String(source.category ?? item.category), description: String(source.description ?? ''), website: String(source.website ?? ''), publicContact: Boolean(source.publicContact) });
  async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/company-workspace/exhibitors/${item.id}/profile`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json() as { error?: string; versionNo?: number }; if (!response.ok) return onMessage(result.error ?? '企业资料提交失败'); onMessage(`企业资料 V${result.versionNo} 已提交审核，公开端继续显示上一版本。`); setTimeout(() => location.reload(), 650); }
  return <form className="company-panel company-form" onSubmit={submit}><div><span>本届企业资料</span><h2>{item.year}届独立资料</h2><p>当前公开：{item.currentProfile ? `V${item.currentProfile.versionNo}` : '无'}　待审核：{item.pendingProfile ? `V${item.pendingProfile.versionNo}` : '无'}</p></div><label>企业中文名<input required value={form.nameZh} onChange={e => setForm({ ...form, nameZh: e.target.value })}/></label><label>国际名称<input value={form.nameIntl} onChange={e => setForm({ ...form, nameIntl: e.target.value })}/></label><label>国家/地区<input required value={form.country} onChange={e => setForm({ ...form, country: e.target.value })}/></label><label>本届参展分类<input required value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}/></label><label className="wide">企业简介<textarea required value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></label><label>网站<input value={form.website} onChange={e => setForm({ ...form, website: e.target.value })}/></label><label className="check-row"><input type="checkbox" checked={form.publicContact} onChange={e => setForm({ ...form, publicContact: e.target.checked })}/> 允许公开审核通过的企业联系方式</label><button className="primary-button" disabled={Boolean(item.pendingProfile)}>{item.pendingProfile ? '已有版本审核中' : '提交企业资料审核'}</button></form>;
}

function ProductEditor({ item, onMessage }: { item: EnterpriseParticipation; onMessage: (value: string) => void }) {
  const [form, setForm] = useState({ name: '', category: '', summary: '' }); async function create(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/company-workspace/exhibitors/${item.id}/products`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json() as { error?: string }; if (!response.ok) return onMessage(result.error ?? '产品提交失败'); onMessage('新产品已提交独立审核。'); setTimeout(() => location.reload(), 650); }
  return <div className="company-product-layout"><form className="company-panel company-form" onSubmit={create}><div><span>新增本届产品</span><h2>产品资料单独审核</h2></div><label>产品名称<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label><label>分类<input required value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}/></label><label className="wide">简介<textarea value={form.summary} onChange={e => setForm({ ...form, summary: e.target.value })}/></label><button className="primary-button">提交产品审核</button><small>价格不进入公开展示。</small></form><section className="company-product-list">{item.products.map(product => <ProductVersionForm key={product.id} product={product} onMessage={onMessage}/>)}</section></div>;
}

function ProductVersionForm({ product, onMessage }: { product: Product; onMessage: (value: string) => void }) { const source = product.pending?.data ?? product.current?.data ?? {}; const [editing, setEditing] = useState(false); const [form, setForm] = useState({ name: String(source.name ?? product.name), category: String(source.category ?? product.category), summary: String(source.summary ?? '') }); async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/company-workspace/products/${product.id}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json() as { error?: string; versionNo?: number }; if (!response.ok) return onMessage(result.error ?? '产品版本提交失败'); onMessage(`产品 V${result.versionNo} 已提交，公开端继续显示上一版本。`); setTimeout(() => location.reload(), 650); } return <article className="company-panel product-version-card"><div><span>{product.category}</span><h3>{product.name}</h3><p>公开：{product.current ? `V${product.current.versionNo}` : '无'}　待审核：{product.pending ? `V${product.pending.versionNo}` : '无'}</p></div>{editing ? <form onSubmit={submit}><label>产品名称<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label><label>分类<input value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}/></label><label>简介<textarea value={form.summary} onChange={e => setForm({ ...form, summary: e.target.value })}/></label><button className="primary-button" disabled={Boolean(product.pending)}>提交新版本</button></form> : <button onClick={() => setEditing(true)} disabled={Boolean(product.pending)}>{product.pending ? '版本审核中' : '编辑并提交新版本'}</button>}</article>; }

function InquiryList({ item, onMessage }: { item: EnterpriseParticipation; onMessage: (value: string) => void }) { const [rows, setRows] = useState(item.inquiries); async function update(id: string, status: 'CONTACTED' | 'CLOSED') { const response = await fetch(`/api/company-workspace/inquiries/${id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status }) }); const result = await response.json() as { error?: string }; if (!response.ok) return onMessage(result.error ?? '询盘处理失败'); setRows(current => current.map(row => row.id === id ? { ...row, status } : row)); onMessage(status === 'CONTACTED' ? '询盘已标记为已联系。' : '询盘已关闭。'); } return <section className="company-panel"><div><span>本届询盘</span><h2>客户联系与线下反馈</h2></div><div className="company-inquiry-list">{rows.length ? rows.map(row => <article key={row.id}><div><strong>{row.customerName}</strong><small>{row.contactPrivate} · {row.createdAt.slice(0, 16).replace('T', ' ')}</small><p>{row.content}</p></div><span>{statusText[row.status] ?? row.status}</span><div><button disabled={row.status !== 'NEW'} onClick={() => update(row.id, 'CONTACTED')}>标记已联系</button><button disabled={row.status === 'CLOSED'} onClick={() => update(row.id, 'CLOSED')}>关闭</button></div></article>) : <p>本届暂无询盘。</p>}</div></section>; }
