'use client';
import { useState } from 'react';

export function EnterpriseLoginPanel({ returnTo }: { returnTo: string }) {
  const [identifier, setIdentifier] = useState('13800002048'); const [challengeId, setChallengeId] = useState(''); const [code, setCode] = useState(''); const [testCode, setTestCode] = useState(''); const [remember, setRemember] = useState(true); const [message, setMessage] = useState('演示企业账号：华南智能制造有限公司 13800002048。');
  async function send() { const response = await fetch('/api/enterprise-auth/otp/send', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ identifier }) }); const result = await response.json() as { error?: string; challengeId?: string; destinationMasked?: string; testCode?: string }; if (!response.ok || !result.challengeId) return setMessage(result.error ?? '验证码发送失败'); setChallengeId(result.challengeId); setTestCode(result.testCode ?? ''); setCode(result.testCode ?? ''); setMessage(`验证码已发送至 ${result.destinationMasked}；本地测试码已自动填入。`); }
  async function verify() { const response = await fetch('/api/enterprise-auth/otp/verify', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ challengeId, code, remember }) }); const result = await response.json() as { error?: string }; if (!response.ok) return setMessage(result.error ?? '登录失败'); location.href = returnTo; }
  return <section className="enterprise-login-card"><span>COMPANY ACCOUNT · PC ALPHA</span><h1>参展企业工作台</h1><p>一家企业只绑定一个账号；同一账号管理历届参展事实，每届资料和产品独立维护。</p><label>企业账号手机号或邮箱<input aria-label="企业账号手机号或邮箱" value={identifier} onChange={event => setIdentifier(event.target.value)} placeholder="手机号 / 邮箱"/></label><button onClick={send} disabled={!identifier}>获取验证码</button>{challengeId ? <><label>验证码<input aria-label="企业账号验证码" inputMode="numeric" maxLength={6} value={code} onChange={event => setCode(event.target.value)}/></label><label className="remember-public"><input type="checkbox" checked={remember} onChange={event => setRemember(event.target.checked)}/> 保持登录状态15天</label><button className="primary-button" onClick={verify} disabled={code.length !== 6}>验证并登录</button></> : null}{testCode ? <aside><strong>本地Alpha测试码</strong><code>{testCode}</code><small>正式环境不会在页面显示验证码。</small></aside> : null}<p role="status">{message}</p></section>;
}
