'use client';

import { useMemo, useState } from 'react';

type EventRow = { id: string; code: string; slug: string; name: string; shortName: string; year: number; city: string; country: string; timezone: string; startAt: string; endAt: string; status: string; ownerName: string; ownerAccountId: string | null; eventType: string; venueText: string; languagesJson: string; memberCount: number; features: Array<{ code: string; enabled: boolean }> };
type Employee = { id: string; name: string; status: string };
type CopyJob = { id: string; sourceEventId: string; targetEventId: string | null; status: string; reportJson: string; createdAt: string };

const statusText: Record<string, string> = { DRAFT: '草稿', PREPARING: '筹备中', ACTIVE: '进行中', ENDED: '已结束', ARCHIVED: '已归档' };
const nextStatus: Record<string, string | undefined> = { DRAFT: 'PREPARING', PREPARING: 'ACTIVE', ACTIVE: 'ENDED', ENDED: 'ARCHIVED', ARCHIVED: 'ENDED' };
const featureNames: Record<string, string> = { PORTAL: '公开门户', REGISTRATION: '报名', EXHIBITOR: '企业参展', MATCHING: '供需洽谈' };

export function EventWorkspace({ initialEvents, employees, copyJobs }: { initialEvents: EventRow[]; employees: Employee[]; copyJobs: CopyJob[] }) {
  const [events, setEvents] = useState(initialEvents);
  const [tab, setTab] = useState<'list' | 'create' | 'copy'>('list');
  const [year, setYear] = useState('ALL');
  const [status, setStatus] = useState('ALL');
  const [message, setMessage] = useState('展会之间业务数据隔离；集团层可按年度与状态汇总。');
  const filtered = useMemo(() => events.filter((item) => (year === 'ALL' || String(item.year) === year) && (status === 'ALL' || item.status === status)), [events, year, status]);
  const years = [...new Set(events.map((item) => item.year))].sort((a, b) => b - a);

  async function patchEvent(id: string, payload: Record<string, unknown>) {
    setMessage('正在保存…');
    const response = await fetch(`/api/events/${id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) });
    const result = await response.json() as { error?: string; status?: string; ownerAccountId?: string; ownerName?: string; featureCode?: string; enabled?: boolean };
    if (!response.ok) return setMessage(result.error ?? '操作失败');
    setEvents((current) => current.map((item) => item.id !== id ? item : ({ ...item, status: result.status ?? item.status, ownerAccountId: result.ownerAccountId ?? item.ownerAccountId, ownerName: result.ownerName ?? item.ownerName, features: result.featureCode ? item.features.map((feature) => feature.code === result.featureCode ? { ...feature, enabled: Boolean(result.enabled) } : feature) : item.features })));
    setMessage('操作成功，变更已写入审计日志。');
  }

  return <>
    <section className="subnav"><button className={tab === 'list' ? 'active' : ''} onClick={() => setTab('list')}>展会列表</button><button className={tab === 'create' ? 'active' : ''} onClick={() => setTab('create')}>创建展会</button><button className={tab === 'copy' ? 'active' : ''} onClick={() => setTab('copy')}>复制往届</button></section>
    <section className="module-summary"><div><span>全部展会</span><strong>{events.length}</strong><small>集团统一管理</small></div><div><span>筹备/进行</span><strong>{events.filter((item) => ['PREPARING', 'ACTIVE'].includes(item.status)).length}</strong><small>当前项目</small></div><div><span>年度</span><strong>{years.length}</strong><small>可下钻筛选</small></div><div><span>复制任务</span><strong>{copyJobs.length}</strong><small>保留复制报告</small></div></section>
    <div className="review-message" role="status">{message}</div>
    {tab === 'list' ? <><section className="event-filters"><label>年度<select value={year} onChange={(event) => setYear(event.target.value)}><option value="ALL">全部年度</option>{years.map((item) => <option value={item} key={item}>{item}</option>)}</select></label><label>状态<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">全部状态</option>{Object.entries(statusText).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><span>显示 {filtered.length} 个项目</span></section><section className="event-grid">{filtered.map((item) => <EventCard key={item.id} item={item} employees={employees} onPatch={patchEvent} onCopy={() => setTab('copy')} />)}</section></> : null}
    {tab === 'create' ? <CreateEventForm employees={employees} onCreated={(event) => { setEvents((current) => [event, ...current]); setMessage('新展会已创建为草稿，尚未公开。'); setTab('list'); }} /> : null}
    {tab === 'copy' ? <CopyEventForm events={events} employees={employees} onCopied={() => { setMessage('复制完成；页面和表单已重置为草稿，业务事实数据未复制。刷新后可查看目标展会。'); setTimeout(() => window.location.reload(), 500); }} /> : null}
  </>;
}

function EventCard({ item, employees, onPatch, onCopy }: { item: EventRow; employees: Employee[]; onPatch: (id: string, payload: Record<string, unknown>) => void; onCopy: () => void }) {
  const [owner, setOwner] = useState(item.ownerAccountId ?? '');
  const [reason, setReason] = useState('项目负责人调整');
  const features = ['PORTAL', 'REGISTRATION', 'EXHIBITOR', 'MATCHING'];
  return <article className="event-card"><div className="event-card-head"><div><span>{item.year} · {item.eventType === 'INTERNAL_ACTIVITY' ? '内部活动' : '线下展会'}</span><h2>{item.shortName}</h2><p>{item.name}</p></div><span className={`state-pill ${item.status.toLowerCase()}`}>{statusText[item.status]}</span></div><dl><div><dt>公开路径</dt><dd>/exhibition/{item.slug}</dd></div><div><dt>时间</dt><dd>{item.startAt.slice(0, 10)} — {item.endAt.slice(0, 10)}</dd></div><div><dt>地点</dt><dd>{item.country} · {item.city || '待填写'}</dd></div><div><dt>负责人/成员</dt><dd>{item.ownerName} · {item.memberCount} 人</dd></div></dl><div className="feature-switches">{features.map((code) => { const current = item.features.find((feature) => feature.code === code)?.enabled ?? false; return <label key={code}><input type="checkbox" checked={current} onChange={(event) => onPatch(item.id, { action: 'FEATURE', featureCode: code, enabled: event.target.checked })}/>{featureNames[code]}</label>; })}</div><div className="event-card-actions"><button onClick={onCopy}>复制为新展会</button>{nextStatus[item.status] ? <button className="primary-button" onClick={() => onPatch(item.id, { action: 'TRANSITION', targetStatus: nextStatus[item.status] })}>{item.status === 'ARCHIVED' ? '恢复为已结束' : `推进至${statusText[nextStatus[item.status]!]}`}</button> : null}</div><details><summary>负责人交接</summary><div className="handover-row"><select aria-label={`${item.shortName}新负责人`} value={owner} onChange={(event) => setOwner(event.target.value)}>{employees.filter((employee) => employee.status === 'ACTIVE').map((employee) => <option value={employee.id} key={employee.id}>{employee.name}</option>)}</select><input aria-label={`${item.shortName}交接原因`} value={reason} onChange={(event) => setReason(event.target.value)}/><button disabled={!owner || owner === item.ownerAccountId} onClick={() => onPatch(item.id, { action: 'HANDOVER', newOwnerAccountId: owner, reason })}>确认交接</button></div></details></article>;
}

function CreateEventForm({ employees, onCreated }: { employees: Employee[]; onCreated: (event: EventRow) => void }) {
  const [form, setForm] = useState({ code: '', slug: '', name: '', shortName: '', year: '2027', city: '', country: '中国', timezone: 'Asia/Shanghai', startAt: '2027-09-01T09:00', endAt: '2027-09-03T18:00', eventType: 'EXHIBITION', venueText: '', ownerAccountId: 'employee-limin' });
  const [message, setMessage] = useState('');
  const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); const response = await fetch('/api/events', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, year: Number(form.year), languages: ['zh-CN'] }) }); const result = await response.json() as { error?: string; id?: string }; if (!response.ok || !result.id) return setMessage(result.error ?? '创建失败'); const owner = employees.find((item) => item.id === form.ownerAccountId); onCreated({ id: result.id, ...form, year: Number(form.year), status: 'DRAFT', ownerName: owner?.name ?? '', languagesJson: '["zh-CN"]', memberCount: 1, features: ['PORTAL', 'REGISTRATION', 'EXHIBITOR'].map((code) => ({ code, enabled: true })) }); }
  return <form className="workspace-form" onSubmit={submit}><div><span className="eyebrow">NEW EVENT</span><h2>从空白创建展会</h2><p>创建后保持草稿状态，公开页面和活动需分别配置、审核和发布。</p></div><div className="form-grid"><label>展会编码<input required value={form.code} onChange={(event) => set('code', event.target.value)} placeholder="CFE-XX-2027"/></label><label>集团网站路径<input required value={form.slug} onChange={(event) => set('slug', event.target.value)} placeholder="2027-city"/></label><label className="span-2">展会全称<input required value={form.name} onChange={(event) => set('name', event.target.value)}/></label><label>展会简称<input required value={form.shortName} onChange={(event) => set('shortName', event.target.value)}/></label><label>类型<select value={form.eventType} onChange={(event) => set('eventType', event.target.value)}><option value="EXHIBITION">线下展会</option><option value="INTERNAL_ACTIVITY">内部活动（论坛/晚宴等）</option></select></label><label>年度<input type="number" value={form.year} onChange={(event) => set('year', event.target.value)}/></label><label>负责人<select value={form.ownerAccountId} onChange={(event) => set('ownerAccountId', event.target.value)}>{employees.filter((item) => item.status === 'ACTIVE').map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>国家/地区<input value={form.country} onChange={(event) => set('country', event.target.value)}/></label><label>城市<input value={form.city} onChange={(event) => set('city', event.target.value)}/></label><label>开始时间<input type="datetime-local" value={form.startAt} onChange={(event) => set('startAt', event.target.value)}/></label><label>结束时间<input type="datetime-local" value={form.endAt} onChange={(event) => set('endAt', event.target.value)}/></label><label className="span-2">场地文字<input value={form.venueText} onChange={(event) => set('venueText', event.target.value)}/></label></div><button className="primary-button" type="submit">创建草稿展会</button><span role="status">{message}</span></form>;
}

function CopyEventForm({ events, employees, onCopied }: { events: EventRow[]; employees: Employee[]; onCopied: () => void }) {
  const source = events[0];
  const [sourceId, setSourceId] = useState(source?.id ?? '');
  const [form, setForm] = useState({ code: '', slug: '', name: '', shortName: '', year: '2027', startAt: '2027-11-18T09:00', endAt: '2027-11-20T18:00', city: source?.city ?? '', country: source?.country ?? '', ownerAccountId: source?.ownerAccountId ?? 'employee-limin', copyPortal: true, copyForms: true, copyFeatures: true });
  const [message, setMessage] = useState('');
  const set = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage('正在复制并生成独立ID…'); const response = await fetch(`/api/events/${sourceId}/copy`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, year: Number(form.year) }) }); const result = await response.json() as { error?: string; report?: { portalPages: number; registrationActivities: number; features: number } }; if (!response.ok) return setMessage(result.error ?? '复制失败'); setMessage(`完成：${result.report?.portalPages ?? 0}个页面、${result.report?.registrationActivities ?? 0}个活动表单、${result.report?.features ?? 0}项功能配置。`); onCopied(); }
  return <form className="workspace-form" onSubmit={submit}><div><span className="eyebrow">COPY EVENT</span><h2>复制往届内容为独立副本</h2><p>报名人员、企业申请、产品、询盘、签到和行为数据固定排除；复制结果重新进入草稿与审核流程。</p></div><div className="form-grid"><label className="span-2">来源展会<select value={sourceId} onChange={(event) => setSourceId(event.target.value)}>{events.map((item) => <option value={item.id} key={item.id}>{item.year} · {item.name}</option>)}</select></label><label>新展会编码<input required value={form.code} onChange={(event) => set('code', event.target.value)}/></label><label>新公开路径<input required value={form.slug} onChange={(event) => set('slug', event.target.value)}/></label><label className="span-2">新展会全称<input required value={form.name} onChange={(event) => set('name', event.target.value)}/></label><label>简称<input required value={form.shortName} onChange={(event) => set('shortName', event.target.value)}/></label><label>年度<input type="number" value={form.year} onChange={(event) => set('year', event.target.value)}/></label><label>开始时间<input type="datetime-local" value={form.startAt} onChange={(event) => set('startAt', event.target.value)}/></label><label>结束时间<input type="datetime-local" value={form.endAt} onChange={(event) => set('endAt', event.target.value)}/></label><label>负责人<select value={form.ownerAccountId} onChange={(event) => set('ownerAccountId', event.target.value)}>{employees.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><div className="copy-options"><label><input type="checkbox" checked={form.copyPortal} onChange={(event) => set('copyPortal', event.target.checked)}/>门户布局与内容</label><label><input type="checkbox" checked={form.copyForms} onChange={(event) => set('copyForms', event.target.checked)}/>活动与表单定义</label><label><input type="checkbox" checked={form.copyFeatures} onChange={(event) => set('copyFeatures', event.target.checked)}/>功能开关</label></div></div><button className="primary-button" type="submit">生成独立副本</button><span role="status">{message}</span></form>;
}
