'use client';

import { FormEvent, useMemo, useState } from 'react';

type Exhibitor = { id: string; enterpriseId: string; nameZh: string; nameIntl: string; country: string; industry: string; contactName: string; contactEmailMasked: string; qualification: string; publish: string; category: string; description: string; currentVersionId: string | null; productCount: number; boothNo: string | null; source: string; profiles: Array<{ id: string; versionNo: number; status: string }> };
type Product = { id: string; exhibitorId: string; name: string; category: string; status: string; enterpriseName: string };
type Inquiry = { id: string; exhibitorId: string; enterpriseName: string; customerName: string; contactMasked: string; contactPrivate: string; content: string; status: string; createdAt: string; handledBy: string | null };
const statusText: Record<string, string> = { PENDING: '待审核', APPROVED: '资格通过', REJECTED: '已退回', DRAFT: '草稿', PUBLISHED: '已公开', RETURNED: '已退回', NEW: '待联系', CONTACTED: '已联系', CLOSED: '已关闭' };

export function ExhibitorWorkspace({ initialExhibitors, initialProducts, initialInquiries }: { initialExhibitors: Exhibitor[]; initialProducts: Product[]; initialInquiries: Inquiry[] }) {
  const [tab, setTab] = useState<'exhibitors' | 'products' | 'inquiries' | 'credentials'>('exhibitors');
  const [exhibitors, setExhibitors] = useState(initialExhibitors); const [products, setProducts] = useState(initialProducts); const [inquiries, setInquiries] = useState(initialInquiries);
  const [message, setMessage] = useState('企业资格和公开资料分别管理；新版本审核期间继续展示旧版本。');
  const [showCreate, setShowCreate] = useState(false);
  const totals = useMemo(() => ({ published: exhibitors.filter((item) => item.publish === 'PUBLISHED' && item.qualification === 'APPROVED').length, pending: exhibitors.filter((item) => item.qualification === 'PENDING').length, pendingProducts: products.filter((item) => item.status === 'DRAFT').length, newInquiries: inquiries.filter((item) => item.status === 'NEW').length }), [exhibitors, products, inquiries]);

  async function exhibitorAction(id: string, action: string, extra: Record<string, unknown> = {}) {
    const response = await fetch(`/api/exhibitors/${id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action, ...extra }) }); const result = await response.json() as { error?: string };
    if (!response.ok) return setMessage(result.error ?? '处理失败');
    setExhibitors((current) => current.map((item) => item.id === id ? { ...item, qualification: action === 'APPROVE_QUALIFICATION' ? 'APPROVED' : item.qualification, publish: action === 'APPROVE_PROFILE' ? 'PUBLISHED' : item.publish, boothNo: action === 'ASSIGN_BOOTH' ? String(extra.boothNo) : item.boothNo } : item));
    setMessage(action === 'APPROVE_QUALIFICATION' ? '企业资格已通过，仍需单独发布企业资料。' : action === 'APPROVE_PROFILE' ? '企业资料已发布到公开门户。' : '展位分配已保存。');
  }
  async function productAction(id: string) { const response = await fetch(`/api/products/${id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'APPROVE' }) }); const result = await response.json() as { error?: string; status?: string }; if (!response.ok) return setMessage(result.error ?? '产品审核失败'); setProducts((current) => current.map((item) => item.id === id ? { ...item, status: result.status ?? item.status } : item)); setMessage('产品资料已独立审核并公开，不展示价格。'); }
  async function inquiryAction(id: string, status: 'CONTACTED' | 'CLOSED') { const response = await fetch(`/api/inquiries/${id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status }) }); const result = await response.json() as { error?: string; handledBy?: string }; if (!response.ok) return setMessage(result.error ?? '询盘处理失败'); setInquiries((current) => current.map((item) => item.id === id ? { ...item, status, handledBy: result.handledBy ?? '当前员工' } : item)); setMessage(status === 'CONTACTED' ? '询盘已标记为已联系。' : '询盘已关闭。'); }

  return <><section className="subnav"><button className={tab === 'exhibitors' ? 'active' : ''} onClick={() => setTab('exhibitors')}>本届参展企业</button><button className={tab === 'products' ? 'active' : ''} onClick={() => setTab('products')}>产品资料</button><button className={tab === 'inquiries' ? 'active' : ''} onClick={() => setTab('inquiries')}>询盘记录</button><button className={tab === 'credentials' ? 'active' : ''} onClick={() => setTab('credentials')}>参展证件（待定）</button></section><section className="module-summary"><div><span>本届企业</span><strong>{exhibitors.length}</strong><small>主档与分届资料分开</small></div><div><span>资格待审</span><strong>{totals.pending}</strong><small>不自动公开</small></div><div><span>已公开</span><strong>{totals.published}</strong><small>门户可见</small></div><div><span>新询盘</span><strong>{totals.newInquiries}</strong><small>企业账号可处理</small></div></section><div className="review-message" role="status">{message}</div>
    {tab === 'exhibitors' ? <section><div className="module-actions"><button className="primary-button" onClick={() => setShowCreate((value) => !value)}>＋ 录入参展企业</button><span>一个企业账号 · 历届参展记录 · 本届资料独立版本</span></div>{showCreate ? <CreateExhibitor onDone={() => { setShowCreate(false); window.location.reload(); }} onMessage={setMessage} /> : null}<div className="card-list">{exhibitors.map((item) => <ExhibitorCard key={item.id} item={item} onAction={exhibitorAction} />)}</div></section> : null}
    {tab === 'products' ? <ProductsTab exhibitors={exhibitors} products={products} onCreated={() => window.location.reload()} onApprove={productAction} onMessage={setMessage} /> : null}
    {tab === 'inquiries' ? <section className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">INQUIRIES</span><h2>企业询盘处理</h2></div><span className="soft-pill">后台与企业账号可见</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>客户</th><th>目标企业</th><th>询盘内容</th><th>时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{inquiries.map((item) => <tr key={item.id}><td><strong>{item.customerName}</strong><small>{item.contactPrivate || item.contactMasked}</small></td><td>{item.enterpriseName}</td><td>{item.content}</td><td>{item.createdAt.slice(0, 16).replace('T', ' ')}</td><td><span className={`state-pill ${item.status.toLowerCase()}`}>{statusText[item.status]}</span></td><td><div className="row-actions"><button disabled={item.status !== 'NEW'} onClick={() => void inquiryAction(item.id, 'CONTACTED')}>标记已联系</button><button disabled={item.status === 'CLOSED'} onClick={() => void inquiryAction(item.id, 'CLOSED')}>关闭</button></div></td></tr>)}</tbody></table></div></section> : null}
    {tab === 'credentials' ? <section className="panel planned-panel"><span>PLANNED</span><h2>参展证件整体待定</h2><p>当前只保留导航和扩展数据边界，不收集身份证号，不实现制证、闸机或设备对接。后续客户访谈确定后再细化。</p></section> : null}
  </>;
}

function ExhibitorCard({ item, onAction }: { item: Exhibitor; onAction: (id: string, action: string, extra?: Record<string, unknown>) => void }) {
  const [booth, setBooth] = useState(item.boothNo ?? ''); const pendingProfile = item.profiles.find((profile) => profile.status === 'PENDING');
  const publiclyVisible = item.qualification === 'APPROVED' && item.publish === 'PUBLISHED';
  return <article className="enterprise-card"><div className="enterprise-logo">{(item.nameIntl || item.nameZh).slice(0, 2).toUpperCase()}</div><div className="enterprise-copy"><span>{item.country} · {item.category || item.industry} · 展位 {item.boothNo ?? '待分配'}</span><h2>{item.nameZh}</h2><p>{item.nameIntl}</p><div><span className={`state-pill ${item.qualification.toLowerCase()}`}>{statusText[item.qualification]}</span><span className={`state-pill ${publiclyVisible ? 'published' : 'draft'}`}>{publiclyVisible ? '门户可见' : '门户隐藏'}</span><span className="soft-pill">{item.productCount} 项产品</span><span className="soft-pill">{item.source}</span></div></div><div className="enterprise-actions"><div><input aria-label={`${item.nameZh}展位号`} value={booth} onChange={(event) => setBooth(event.target.value)} placeholder="展位号"/><button onClick={() => onAction(item.id, 'ASSIGN_BOOTH', { boothNo: booth })}>分配</button></div><button disabled={item.qualification !== 'PENDING'} onClick={() => onAction(item.id, 'APPROVE_QUALIFICATION')}>资格通过</button><button className="primary-button" disabled={!pendingProfile || item.qualification !== 'APPROVED'} onClick={() => onAction(item.id, 'APPROVE_PROFILE')}>发布待审资料</button></div></article>;
}

function CreateExhibitor({ onDone, onMessage }: { onDone: () => void; onMessage: (value: string) => void }) {
  const [form, setForm] = useState({ nameZh: '', nameIntl: '', country: '中国', industry: '', category: '', contactName: '', accountContact: '', source: '工作人员录入' });
  async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch('/api/exhibitors', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json() as { error?: string }; if (!response.ok) return onMessage(result.error ?? '录入失败'); onMessage('企业主档、分届参展记录和待审资料V1已创建。'); onDone(); }
  return <form className="panel quick-create-form" onSubmit={submit}><label>企业中文名<input required value={form.nameZh} onChange={(event) => setForm({ ...form, nameZh: event.target.value })}/></label><label>国际名称<input value={form.nameIntl} onChange={(event) => setForm({ ...form, nameIntl: event.target.value })}/></label><label>国家/地区<input required value={form.country} onChange={(event) => setForm({ ...form, country: event.target.value })}/></label><label>行业<input value={form.industry} onChange={(event) => setForm({ ...form, industry: event.target.value })}/></label><label>参展分类<input value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}/></label><label>企业联络人<input value={form.contactName} onChange={(event) => setForm({ ...form, contactName: event.target.value })}/></label><label>账号联系方式<input required value={form.accountContact} onChange={(event) => setForm({ ...form, accountContact: event.target.value })}/></label><button className="primary-button" type="submit">创建并提交待审资料</button></form>;
}

function ProductsTab({ exhibitors, products, onCreated, onApprove, onMessage }: { exhibitors: Exhibitor[]; products: Product[]; onCreated: () => void; onApprove: (id: string) => void; onMessage: (value: string) => void }) {
  const [form, setForm] = useState({ eventExhibitorId: exhibitors[0]?.id ?? '', name: '', category: '', summary: '' });
  async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch('/api/products', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json() as { error?: string }; if (!response.ok) return onMessage(result.error ?? '产品提交失败'); onMessage('产品V1已提交独立审核。'); onCreated(); }
  return <section className="content-grid"><form className="panel quick-product-form" onSubmit={submit}><div className="panel-head"><div><span className="eyebrow">NEW PRODUCT</span><h2>提交产品资料</h2></div></div><label>所属参展企业<select value={form.eventExhibitorId} onChange={(event) => setForm({ ...form, eventExhibitorId: event.target.value })}>{exhibitors.map((item) => <option key={item.id} value={item.id}>{item.nameZh}</option>)}</select></label><label>产品名称<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}/></label><label>产品分类<input required value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}/></label><label>产品简介<textarea value={form.summary} onChange={(event) => setForm({ ...form, summary: event.target.value })}/></label><button className="primary-button" type="submit">提交产品审核</button><p>价格字段不进入公开资料。</p></form><div className="panel"><div className="panel-head"><div><span className="eyebrow">PRODUCTS</span><h2>产品列表</h2></div></div><div className="product-admin-list">{products.map((item) => <article key={item.id}><div><strong>{item.name}</strong><span>{item.enterpriseName} · {item.category}</span></div><span className={`state-pill ${item.status.toLowerCase()}`}>{statusText[item.status]}</span><button disabled={item.status !== 'DRAFT'} onClick={() => onApprove(item.id)}>审核并公开</button></article>)}</div></div></section>;
}
