'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type Employee = { id: string; name: string; mobile: string; email: string; status: string; lastLoginAt: string | null };
type EventOption = { id: string; name: string; year: number };
type Member = { id: string; eventId: string; eventName: string; accountId: string; employeeName: string; roleCode: string; permissionsJson: string; isReviewer: boolean; status: string };
type Me = { account?: { name: string; memberships: Array<{ eventId: string; roleCode: string; permissions: string[]; isReviewer: boolean }> }; error?: string };
const roleNames: Record<string, string> = { EVENT_ADMIN: '项目管理员', CONTENT_EDITOR: '内容编辑', REVIEWER: '审核员', OPERATIONS: '运营人员', DATA_VIEWER: '数据查看' };

export function IamWorkspace({ initialEmployees, events, initialMembers }: { initialEmployees: Employee[]; events: EventOption[]; initialMembers: Member[] }) {
  const [employees, setEmployees] = useState(initialEmployees); const [members, setMembers] = useState(initialMembers);
  const [tab, setTab] = useState<'employees' | 'members' | 'roles'>('employees'); const [message, setMessage] = useState('权限按集团或展会范围授权；员工可同时加入多个展会。'); const [me, setMe] = useState<Me | null>(null);
  useEffect(() => { fetch('/api/me', { cache: 'no-store' }).then(async (response) => ({ ok: response.ok, body: await response.json() as Me })).then(({ ok, body }) => setMe(ok ? body : { error: body.error })).catch(() => setMe({ error: '会话查询失败' })); }, []);
  const activeCount = employees.filter((item) => item.status === 'ACTIVE').length;
  const reviewerCount = members.filter((item) => item.status === 'ACTIVE' && item.isReviewer).length;
  async function toggleEmployee(employee: Employee) { const status = employee.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE'; const response = await fetch(`/api/iam/employees/${employee.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status }) }); const result = await response.json() as { error?: string }; if (!response.ok) return setMessage(result.error ?? '操作失败'); setEmployees((current) => current.map((item) => item.id === employee.id ? { ...item, status } : item)); setMessage(status === 'DISABLED' ? '账号已停用，所有未结束会话已撤销。' : '账号已重新启用。'); }
  return <><section className="subnav"><button className={tab === 'employees' ? 'active' : ''} onClick={() => setTab('employees')}>员工账号</button><button className={tab === 'members' ? 'active' : ''} onClick={() => setTab('members')}>展会成员</button><button className={tab === 'roles' ? 'active' : ''} onClick={() => setTab('roles')}>角色权限包</button></section><section className="module-summary"><div><span>员工账号</span><strong>{employees.length}</strong><small>无固定组织层级</small></div><div><span>启用账号</span><strong>{activeCount}</strong><small>停用即撤销会话</small></div><div><span>展会成员关系</span><strong>{members.length}</strong><small>同一员工可多项目</small></div><div><span>审核员标记</span><strong>{reviewerCount}</strong><small>仍需遵循他人审核</small></div></section><div className="session-strip"><div><strong>{me?.account ? `当前会话：${me.account.name}` : '当前浏览器尚未建立员工会话'}</strong><span>{me?.account ? `${me.account.memberships.length} 个展会成员身份` : '请先验证身份后使用后台业务功能'}</span></div><Link href="/login">{me?.account ? '重新验证身份' : '测试验证码登录'} →</Link></div><div className="review-message" role="status">{message}</div>{tab === 'employees' ? <EmployeePanel employees={employees} onCreated={(employee) => setEmployees((current) => [...current, employee])} onToggle={toggleEmployee} setMessage={setMessage}/> : null}{tab === 'members' ? <MemberPanel employees={employees} events={events} members={members} setMembers={setMembers} setMessage={setMessage}/> : null}{tab === 'roles' ? <RolePanel/> : null}</>;
}

function EmployeePanel({ employees, onCreated, onToggle, setMessage }: { employees: Employee[]; onCreated: (employee: Employee) => void; onToggle: (employee: Employee) => void; setMessage: (value: string) => void }) {
  const [form, setForm] = useState({ name: '', mobile: '', email: '' });
  async function submit(event: React.FormEvent) { event.preventDefault(); const response = await fetch('/api/iam/employees', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json() as { error?: string; id?: string }; if (!response.ok || !result.id) return setMessage(result.error ?? '创建失败'); onCreated({ id: result.id, ...form, status: 'ACTIVE', lastLoginAt: null }); setForm({ name: '', mobile: '', email: '' }); setMessage('员工账号已创建，可继续加入一个或多个展会。'); }
  return <><form className="quick-create-form" onSubmit={submit}><label>姓名<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}/></label><label>手机号<input required value={form.mobile} onChange={(event) => setForm({ ...form, mobile: event.target.value })}/></label><label>邮箱<input type="email" required value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })}/></label><button className="primary-button" type="submit">＋ 创建员工</button></form><section className="panel table-panel"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>员工</th><th>手机号</th><th>邮箱</th><th>最近登录</th><th>状态</th><th>操作</th></tr></thead><tbody>{employees.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.id}</small></td><td>{item.mobile}</td><td>{item.email}</td><td>{item.lastLoginAt?.slice(0, 16).replace('T', ' ') ?? '尚未登录'}</td><td><span className={`state-pill ${item.status === 'ACTIVE' ? 'approved' : 'withdrawn'}`}>{item.status === 'ACTIVE' ? '启用' : '停用'}</span></td><td><button onClick={() => onToggle(item)}>{item.status === 'ACTIVE' ? '停用并撤销会话' : '重新启用'}</button></td></tr>)}</tbody></table></div></section></>;
}

function MemberPanel({ employees, events, members, setMembers, setMessage }: { employees: Employee[]; events: EventOption[]; members: Member[]; setMembers: React.Dispatch<React.SetStateAction<Member[]>>; setMessage: (value: string) => void }) {
  const [form, setForm] = useState({ eventId: events[0]?.id ?? '', accountId: employees.find((item) => item.status === 'ACTIVE')?.id ?? '', roleCode: 'OPERATIONS', isReviewer: false });
  const eventMap = useMemo(() => Object.fromEntries(events.map((item) => [item.id, item.name])), [events]); const employeeMap = useMemo(() => Object.fromEntries(employees.map((item) => [item.id, item.name])), [employees]);
  async function add(event: React.FormEvent) { event.preventDefault(); const response = await fetch('/api/iam/members', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json() as { error?: string; id?: string; permissions?: string[] }; if (!response.ok || !result.id) return setMessage(result.error ?? '添加失败'); setMembers((current) => [...current, { id: result.id!, ...form, eventName: eventMap[form.eventId], employeeName: employeeMap[form.accountId], permissionsJson: JSON.stringify(result.permissions), status: 'ACTIVE' }]); setMessage('项目成员已添加，权限包已写入成员关系。'); }
  async function change(item: Member, roleCode: string, isReviewer = item.isReviewer) { const response = await fetch('/api/iam/members', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ memberId: item.id, roleCode, isReviewer }) }); const result = await response.json() as { error?: string; permissions?: string[] }; if (!response.ok) return setMessage(result.error ?? '调整失败'); setMembers((current) => current.map((member) => member.id === item.id ? { ...member, roleCode, isReviewer, permissionsJson: JSON.stringify(result.permissions) } : member)); setMessage('成员角色与审核员标记已更新并审计。'); }
  return <><form className="member-add-form" onSubmit={add}><label>展会<select value={form.eventId} onChange={(event) => setForm({ ...form, eventId: event.target.value })}>{events.map((item) => <option value={item.id} key={item.id}>{item.year} · {item.name}</option>)}</select></label><label>员工<select value={form.accountId} onChange={(event) => setForm({ ...form, accountId: event.target.value })}>{employees.filter((item) => item.status === 'ACTIVE').map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>角色<select value={form.roleCode} onChange={(event) => setForm({ ...form, roleCode: event.target.value })}>{Object.entries(roleNames).map(([code, name]) => <option value={code} key={code}>{name}</option>)}</select></label><label className="inline-check"><input type="checkbox" checked={form.isReviewer} onChange={(event) => setForm({ ...form, isReviewer: event.target.checked })}/>加入审核员池</label><button className="primary-button">添加成员</button></form><section className="member-list">{members.map((item) => <article key={item.id}><div><span>{item.eventName}</span><strong>{item.employeeName}</strong><small>{JSON.parse(item.permissionsJson).join(' · ')}</small></div><select aria-label={`${item.employeeName}在${item.eventName}的角色`} value={item.roleCode} onChange={(event) => change(item, event.target.value)}>{Object.entries(roleNames).map(([code, name]) => <option value={code} key={code}>{name}</option>)}</select><label><input type="checkbox" checked={item.isReviewer} onChange={(event) => change(item, item.roleCode, event.target.checked)}/>审核员</label></article>)}</section></>;
}

function RolePanel() { const roles = [{ code: 'EVENT_ADMIN', name: '项目管理员', permissions: '展会配置、成员、审核、强制撤回' }, { code: 'CONTENT_EDITOR', name: '内容编辑', permissions: '门户和内容编辑、提交审核' }, { code: 'REVIEWER', name: '审核员', permissions: '领取、通过、退回；不得审核本人提交' }, { code: 'OPERATIONS', name: '运营人员', permissions: '报名、企业、产品、签到' }, { code: 'DATA_VIEWER', name: '数据查看', permissions: '默认统计和非敏感导出' }]; return <section className="role-grid">{roles.map((role) => <article key={role.code}><span>{role.code}</span><h2>{role.name}</h2><p>{role.permissions}</p><small>Alpha内置权限包 · 后续支持集团管理员调整</small></article>)}</section>; }
