'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';

type Post = { id: string; publisherName: string; publisherType: string; postType: string; title: string; category: string; countriesJson: string; description: string; reviewStatus: string; submittedBy: string; approvedBy: string | null; createdAt: string };
type Appointment = { id: string; inviterName: string; inviteeName: string; proposedStart: string; proposedEnd: string; locationPreference: string; confirmedStart: string | null; confirmedEnd: string | null; confirmedLocation: string | null; status: string; responses: Array<{ id: string; action: string; responderName: string; createdAt: string }> };
type Batch = { id: string; name: string; status: string; submitterName: string; reviewerName: string | null; conflictReportJson: string; schedules: Array<{ id: string; participantA: string; participantB: string; startAt: string; endAt: string; locationText: string; publishStatus: string }> };
const statusText: Record<string,string> = { PENDING:'待审核',PUBLISHED:'已发布',RETURNED:'已退回',PROPOSED:'待回应',COUNTERED:'建议新时间',ACCEPTED:'已接受',REJECTED:'已拒绝',CANCELED:'已取消',DRAFT:'草稿' };

export function MatchingWorkspace({ event, initialPosts, initialAppointments, initialBatches }: { event: { id: string; name: string; startAt: string; endAt: string }; initialPosts: Post[]; initialAppointments: Appointment[]; initialBatches: Batch[] }) {
  const [tab,setTab]=useState<'posts'|'appointments'|'schedules'|'ai'>('posts'); const [posts,setPosts]=useState(initialPosts); const [appointments,setAppointments]=useState(initialAppointments); const [batches,setBatches]=useState(initialBatches); const [message,setMessage]=useState('线下面谈业务：预约接受后生效，人工排期发布前再次检查冲突。');
  const accepted=useMemo(()=>appointments.filter(item=>item.status==='ACCEPTED'),[appointments]);
  return <><section className="subnav"><button className={tab==='posts'?'active':''} onClick={()=>setTab('posts')}>供需信息</button><button className={tab==='appointments'?'active':''} onClick={()=>setTab('appointments')}>自由预约</button><button className={tab==='schedules'?'active':''} onClick={()=>setTab('schedules')}>人工统一排期</button><button className={tab==='ai'?'active':''} onClick={()=>setTab('ai')}>AI配对（待定）</button></section><section className="module-summary"><div><span>已发布供需</span><strong>{posts.filter(item=>item.reviewStatus==='PUBLISHED').length}</strong><small>审核后公开</small></div><div><span>待回应预约</span><strong>{appointments.filter(item=>['PROPOSED','COUNTERED'].includes(item.status)).length}</strong><small>不占正式时段</small></div><div><span>已接受预约</span><strong>{accepted.length}</strong><small>进入人工排期</small></div><div><span>已发布场次</span><strong>{batches.flatMap(item=>item.schedules).filter(item=>item.publishStatus==='PUBLISHED').length}</strong><small>现场可查询</small></div></section><div className="review-message" role="status">{message}</div>{tab==='posts'?<PostsPanel posts={posts} setPosts={setPosts} setMessage={setMessage}/>:null}{tab==='appointments'?<AppointmentsPanel event={event} appointments={appointments} setAppointments={setAppointments} setMessage={setMessage}/>:null}{tab==='schedules'?<SchedulesPanel accepted={accepted} batches={batches} setBatches={setBatches} setMessage={setMessage}/>:null}{tab==='ai'?<section className="panel planned-panel"><span>TALK-TBD-001</span><h2>AI配对能力等待客户访谈</h2><p>当前只建设人工筛选、预约、冲突检查和排期发布。后续可接入建议分数、推荐理由和人工调整记录。</p></section>:null}</>;
}

function PostsPanel({posts,setPosts,setMessage}:{posts:Post[];setPosts:React.Dispatch<React.SetStateAction<Post[]>>;setMessage:(v:string)=>void}){
  const [form,setForm]=useState({publisherName:'华南智能制造有限公司',publisherType:'ENTERPRISE',postType:'DEMAND',title:'',category:'技术装备',countries:'摩洛哥',description:''});
  async function create(e:React.FormEvent){e.preventDefault();const response=await fetch('/api/matching/posts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,countries:form.countries.split(/[,，]/).map(v=>v.trim()).filter(Boolean)})});const result=await response.json() as {error?:string;id?:string};if(!response.ok||!result.id)return setMessage(result.error??'提交失败');setPosts(current=>[{id:result.id!,...form,countriesJson:JSON.stringify(form.countries.split(/[,，]/)),reviewStatus:'PENDING',submittedBy:'当前员工',approvedBy:null,createdAt:new Date().toISOString()},...current]);setMessage('供需信息已提交，必须由另一员工审核后公开。');}
  async function review(item:Post,action:'APPROVE'|'RETURN'){const response=await fetch(`/api/matching/posts/${item.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action})});const result=await response.json() as {error?:string;reviewStatus?:string};if(!response.ok)return setMessage(result.error??'审核失败');setPosts(current=>current.map(post=>post.id===item.id?{...post,reviewStatus:result.reviewStatus??post.reviewStatus,approvedBy:'当前审核人'}:post));setMessage(action==='APPROVE'?'供需信息已发布。':'供需信息已退回。');}
  return <><form className="matching-form" onSubmit={create}><label>发布方<input value={form.publisherName} onChange={e=>setForm({...form,publisherName:e.target.value})}/></label><label>类型<select value={form.postType} onChange={e=>setForm({...form,postType:e.target.value})}><option value="DEMAND">采购需求</option><option value="SUPPLY">供应能力</option><option value="COOPERATION">合作</option><option value="INVESTMENT">投资</option></select></label><label>分类<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>目标国家<input value={form.countries} onChange={e=>setForm({...form,countries:e.target.value})}/></label><label className="wide">标题<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="wide">详细说明<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="primary-button">提交审核</button></form><section className="matching-list">{posts.map(item=><article key={item.id}><div><span>{item.postType} · {item.category} · {JSON.parse(item.countriesJson).join(' / ')}</span><h2>{item.title}</h2><p>{item.publisherName} · {item.description}</p></div><span className={`state-pill ${item.reviewStatus.toLowerCase()}`}>{statusText[item.reviewStatus]}</span><div className="row-actions"><button disabled={item.reviewStatus!=='PENDING'} onClick={()=>review(item,'RETURN')}>退回</button><button disabled={item.reviewStatus!=='PENDING'} onClick={()=>review(item,'APPROVE')}>审核发布</button></div></article>)}</section></>;
}

function AppointmentsPanel({event,appointments,setAppointments,setMessage}:{event:{startAt:string;endAt:string};appointments:Appointment[];setAppointments:React.Dispatch<React.SetStateAction<Appointment[]>>;setMessage:(v:string)=>void}){
  const [form,setForm]=useState({inviterName:'李敏',inviteeName:'华南智能制造有限公司',proposedStart:event.startAt.slice(0,16),proposedEnd:event.startAt.slice(0,11)+'10:00',locationPreference:'现场洽谈区'});
  async function create(e:React.FormEvent){e.preventDefault();const response=await fetch('/api/matching/appointments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,sourceType:'MANUAL'})});const result=await response.json() as {error?:string;id?:string};if(!response.ok||!result.id)return setMessage(result.error??'创建失败');setAppointments(current=>[{id:result.id!,...form,confirmedStart:null,confirmedEnd:null,confirmedLocation:null,status:'PROPOSED',responses:[]},...current]);setMessage('预约邀请已创建，尚未占用正式时段。');}
  async function respond(item:Appointment,action:'ACCEPT'|'REJECT'|'COUNTER'|'CANCEL'){const response=await fetch(`/api/matching/appointments/${item.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action,responderName:action==='CANCEL'?item.inviterName:item.inviteeName,proposedStart:item.proposedStart,proposedEnd:item.proposedEnd,locationText:item.locationPreference})});const result=await response.json() as {error?:string;status?:string;conflicts?:Array<{reason:string}>};if(!response.ok)return setMessage(result.conflicts?.map(c=>c.reason).join('；')||result.error||'处理失败');setAppointments(current=>current.map(appt=>appt.id===item.id?{...appt,status:result.status??appt.status,confirmedStart:action==='ACCEPT'?appt.proposedStart:null,confirmedEnd:action==='ACCEPT'?appt.proposedEnd:null,confirmedLocation:action==='ACCEPT'?appt.locationPreference:null}:appt));setMessage(action==='ACCEPT'?'预约已由被邀请方接受并通过冲突检查。':`预约状态已更新为${result.status}`);}
  return <><form className="matching-form" onSubmit={create}><label>邀请方<input value={form.inviterName} onChange={e=>setForm({...form,inviterName:e.target.value})}/></label><label>被邀请方<input value={form.inviteeName} onChange={e=>setForm({...form,inviteeName:e.target.value})}/></label><label>候选开始<input type="datetime-local" value={form.proposedStart} onChange={e=>setForm({...form,proposedStart:e.target.value})}/></label><label>候选结束<input type="datetime-local" value={form.proposedEnd} onChange={e=>setForm({...form,proposedEnd:e.target.value})}/></label><label className="wide">地点偏好<input value={form.locationPreference} onChange={e=>setForm({...form,locationPreference:e.target.value})}/></label><button className="primary-button">发起线下预约</button></form><section className="appointment-list">{appointments.map(item=><article key={item.id}><div><span>{item.proposedStart.replace('T',' ')} — {item.proposedEnd.slice(11)} · {item.locationPreference}</span><h2>{item.inviterName} ⇄ {item.inviteeName}</h2><small>只有双方接受后才占用正式时段</small></div><span className={`state-pill ${item.status.toLowerCase()}`}>{statusText[item.status]}</span><div className="row-actions"><button disabled={!['PROPOSED','COUNTERED'].includes(item.status)} onClick={()=>respond(item,'REJECT')}>拒绝</button><button disabled={!['PROPOSED','COUNTERED'].includes(item.status)} onClick={()=>respond(item,'COUNTER')}>建议时间</button><button disabled={!['PROPOSED','COUNTERED'].includes(item.status)} onClick={()=>respond(item,'ACCEPT')}>接受</button></div></article>)}</section></>;
}

function SchedulesPanel({accepted,batches,setBatches,setMessage}:{accepted:Appointment[];batches:Batch[];setBatches:React.Dispatch<React.SetStateAction<Batch[]>>;setMessage:(v:string)=>void}){
  const [name,setName]=useState('首日采购对接排期');const [selected,setSelected]=useState<string[]>(accepted.map(item=>item.id));
  async function create(){const response=await fetch('/api/matching/batches',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,appointmentIds:selected,locationPrefix:'洽谈桌'})});const result=await response.json() as {error?:string;id?:string;scheduleCount?:number;conflicts?:Array<{reason:string}>};if(!response.ok||!result.id)return setMessage(result.conflicts?.map(c=>c.reason).join('；')||result.error||'创建失败');setBatches(current=>[{id:result.id!,name,status:'DRAFT',submitterName:'当前员工',reviewerName:null,conflictReportJson:'[]',schedules:accepted.filter(item=>selected.includes(item.id)).map((item,index)=>({id:`pending-${index}`,participantA:item.inviterName,participantB:item.inviteeName,startAt:item.confirmedStart!,endAt:item.confirmedEnd!,locationText:`洽谈桌 ${String(index+1).padStart(2,'0')}`,publishStatus:'DRAFT'}))},...current]);setMessage(`排期草稿已创建，共${result.scheduleCount}场。`);}
  async function action(item:Batch,action:'SUBMIT'|'PUBLISH'|'RETURN'){const response=await fetch(`/api/matching/batches/${item.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action})});const result=await response.json() as {error?:string;status?:string;conflicts?:Array<{reason:string}>};if(!response.ok)return setMessage(result.conflicts?.map(c=>c.reason).join('；')||result.error||'操作失败');setBatches(current=>current.map(batch=>batch.id===item.id?{...batch,status:result.status??batch.status,schedules:action==='PUBLISH'?batch.schedules.map(schedule=>({...schedule,publishStatus:'PUBLISHED'})):batch.schedules}:batch));setMessage(action==='SUBMIT'?'排期已提交，必须由另一员工审核。':action==='PUBLISH'?'排期已发布，现场查询可见。':'排期已退回。');}
  return <><section className="schedule-create"><div><h2>从已接受预约建立人工排期</h2><p>AI配对保持待定；工作人员选择、安排地点并发布。</p></div><input value={name} onChange={e=>setName(e.target.value)}/><div>{accepted.map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>setSelected(current=>e.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/>{item.inviterName} ⇄ {item.inviteeName} · {item.confirmedStart?.replace('T',' ')}</label>)}</div><button className="primary-button" disabled={!selected.length} onClick={create}>生成排期草稿</button></section><section className="batch-list">{batches.map(item=><article key={item.id}><div className="batch-head"><div><span>{item.submitterName}提交 · 审核人 {item.reviewerName??'待定'}</span><h2>{item.name}</h2></div><span className={`state-pill ${item.status.toLowerCase()}`}>{statusText[item.status]}</span><div className="row-actions"><button disabled={item.status!=='DRAFT'} onClick={()=>action(item,'SUBMIT')}>提交审核</button><button disabled={item.status!=='PENDING'} onClick={()=>action(item,'RETURN')}>退回</button><button disabled={item.status!=='PENDING'} onClick={()=>action(item,'PUBLISH')}>审核发布</button></div></div><div className="schedule-table">{item.schedules.map(schedule=><div key={schedule.id}><time>{schedule.startAt.replace('T',' ')}—{schedule.endAt.slice(11)}</time><strong>{schedule.participantA} ⇄ {schedule.participantB}</strong><span>{schedule.locationText}</span></div>)}</div></article>)}</section><Link className="button-link ghost-button" href="/my-schedule">打开手机现场查询 →</Link></>;
}
