'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';

type Post = { id: string; publisherName: string; publisherEnterpriseId: string | null; postType: string; title: string; category: string; countriesJson: string; description: string; reviewStatus: string };
type Enterprise = { id: string; name: string; boothNo: string | null };
type Appointment = { id: string; inviterName: string; inviteeName: string; proposedStart: string; proposedEnd: string; locationPreference: string; status: string };
const postStatusText: Record<string,string> = { PENDING:'待审核', PUBLISHED:'已公开', REJECTED:'已退回', RETURNED:'已退回' };
const appointmentStatusText: Record<string,string> = { PROPOSED:'待回应', COUNTERED:'待确认新时间', ACCEPTED:'已接受', REJECTED:'已拒绝', CANCELED:'已取消' };

export function PublicMatchingClient({ eventId, eventSlug, eventStart, loggedIn, posts, ownPosts, enterprises, appointments }: { eventId:string; eventSlug:string; eventStart:string; loggedIn:boolean; posts:Post[]; ownPosts:Post[]; enterprises:Enterprise[]; appointments:Appointment[] }) {
  const day = eventStart.slice(0,10);
  const [message,setMessage]=useState('公开供需可匿名浏览；发布和预约需要登录。');
  const [post,setPost]=useState({postType:'PURCHASE',category:'商务合作',country:'摩洛哥',title:'',description:''});
  const [appointment,setAppointment]=useState({inviteeEnterpriseId:enterprises[0]?.id??'',sourcePostId:'',proposedStart:`${day}T10:30`,proposedEnd:`${day}T11:30`,locationPreference:'现场洽谈区'});
  function choosePost(id:string){const value=posts.find(item=>item.id===id);setAppointment(current=>({...current,sourcePostId:id,inviteeEnterpriseId:value?.publisherEnterpriseId??current.inviteeEnterpriseId}));document.getElementById('public-appointment-form')?.scrollIntoView({behavior:'smooth'});}
  function applyTimeSlot(value:string){if(!value)return;const[start,end]=value.split('|');setAppointment(current=>({...current,proposedStart:start,proposedEnd:end}));}
  async function submitPost(event:FormEvent){event.preventDefault();const response=await fetch('/api/public-matching/posts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventId,postType:post.postType,category:post.category,countries:[post.country],title:post.title,description:post.description})});const result=await response.json() as {error?:string};if(!response.ok)return setMessage(result.error??'提交失败');setMessage('供需已提交审核，审核通过后进入公开市场。');location.reload();}
  async function submitAppointment(event:FormEvent){event.preventDefault();const response=await fetch('/api/public-matching/appointments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventId,...appointment})});const result=await response.json() as {error?:string};if(!response.ok)return setMessage(result.error??'预约失败');setMessage('线下面谈邀请已发出，等待企业响应。');location.reload();}
  async function cancel(id:string){const response=await fetch(`/api/public-matching/appointments/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'CANCEL'})});const result=await response.json() as {error?:string};if(!response.ok)return setMessage(result.error??'取消失败');location.reload();}
  return <>
    <section className="public-matching-market"><div className="section-heading"><div><span>SUPPLY & DEMAND</span><h2>本届公开供需</h2></div><p>只展示审核通过的内容，私人预约不会公开。</p></div>{posts.length?<div className="public-matching-grid">{posts.map(item=><article key={item.id}><small>{item.postType} · {item.category}</small><h3>{item.title}</h3><p>{item.description}</p><footer><span>{item.publisherName}</span>{loggedIn&&item.publisherEnterpriseId?<button onClick={()=>choosePost(item.id)}>发起线下面谈</button>:null}</footer></article>)}</div>:<div className="empty-state">本届暂无已发布供需。</div>}</section>
    {!loggedIn?<section className="public-matching-gate"><h2>登录后参与供需与预约</h2><p>可提交供需审核，或向已公开参展企业发起线下面谈。</p><Link className="portal-primary button-link" href={`/exhibition/${eventSlug}/login?returnTo=/exhibition/${eventSlug}/matching`}>观众登录</Link></section>:<>
      <p className="public-matching-status" role="status">{message}</p>
      <section className="public-matching-workbench"><form onSubmit={submitPost}><div><span>MY POST</span><h2>发布供需</h2></div><label>类型<select value={post.postType} onChange={e=>setPost({...post,postType:e.target.value})}><option value="PURCHASE">采购需求</option><option value="SUPPLY">供应能力</option><option value="COOPERATION">合作</option><option value="INVESTMENT">投资</option></select></label><label>分类<input value={post.category} onChange={e=>setPost({...post,category:e.target.value})}/></label><label>目标国家<input value={post.country} onChange={e=>setPost({...post,country:e.target.value})}/></label><label className="wide">标题<input required value={post.title} onChange={e=>setPost({...post,title:e.target.value})}/></label><label className="wide">详细说明<textarea required value={post.description} onChange={e=>setPost({...post,description:e.target.value})}/></label><button className="portal-primary">提交审核</button></form>
      <form id="public-appointment-form" onSubmit={submitAppointment}><div><span>OFFLINE MEETING</span><h2>预约参展企业</h2></div><label>关联企业供需<select value={appointment.sourcePostId} onChange={e=>choosePost(e.target.value)}><option value="">不关联</option>{posts.filter(item=>item.publisherEnterpriseId).map(item=><option key={item.id} value={item.id}>{item.publisherName} · {item.title}</option>)}</select></label><label>被邀请企业<select required value={appointment.inviteeEnterpriseId} onChange={e=>setAppointment({...appointment,inviteeEnterpriseId:e.target.value,sourcePostId:''})}>{enterprises.map(item=><option key={item.id} value={item.id}>{item.name} · {item.boothNo??'展位待分配'}</option>)}</select></label><label className="wide">快速时间段<select defaultValue="" onChange={e=>applyTimeSlot(e.target.value)}><option value="">手动填写或选择</option><option value={`${day}T09:00|${day}T10:00`}>首日 09:00—10:00</option><option value={`${day}T10:30|${day}T11:30`}>首日 10:30—11:30</option><option value={`${day}T14:00|${day}T15:00`}>首日 14:00—15:00</option></select></label><label>候选开始<input type="datetime-local" required value={appointment.proposedStart} onChange={e=>setAppointment({...appointment,proposedStart:e.target.value})}/></label><label>候选结束<input type="datetime-local" required value={appointment.proposedEnd} onChange={e=>setAppointment({...appointment,proposedEnd:e.target.value})}/></label><label className="wide">地点偏好<input value={appointment.locationPreference} onChange={e=>setAppointment({...appointment,locationPreference:e.target.value})}/></label><button className="portal-primary" disabled={!enterprises.length}>发起预约</button></form></section>
      <section className="public-matching-mine"><div><span>MY ACTIVITY</span><h2>我的供需与预约</h2></div><div className="public-matching-grid">{ownPosts.map(item=><article key={item.id}><small>供需 · {postStatusText[item.reviewStatus]??item.reviewStatus}</small><h3>{item.title}</h3><p>{item.description}</p></article>)}{appointments.map(item=><article key={item.id}><small>预约 · {appointmentStatusText[item.status]??item.status}</small><h3>{item.inviterName} ⇄ {item.inviteeName}</h3><p>{item.proposedStart.replace('T',' ')}—{item.proposedEnd.slice(11)} · {item.locationPreference}</p>{['PROPOSED','COUNTERED','ACCEPTED'].includes(item.status)?<button onClick={()=>cancel(item.id)}>取消预约</button>:null}</article>)}{!ownPosts.length&&!appointments.length?<p>暂无记录。</p>:null}</div></section>
    </>}
  </>;
}
